<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DMView</name>
   <tag></tag>
   <elementGuidId>47c12371-c776-4493-8482-59c747d503f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ckbdashboardmanagerview</value>
      <webElementGuid>e3a53521-1216-40b8-8b86-85c75177a746</webElementGuid>
   </webElementProperties>
</WebElementEntity>
