<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Description</name>
   <tag></tag>
   <elementGuidId>b9c9f746-e4b3-40f6-9f57-0489c19cff05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='tmldatagroupdescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tmldatagroupdescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7a58a884-360c-4302-9749-4de6b538e1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tmldatagroupdescription</value>
      <webElementGuid>8ae82bd8-a6e7-4ccc-85ad-4c7b9e72f6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataGroupDescription</value>
      <webElementGuid>2d702106-5ccd-4442-a3c4-c703b0ada278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control resize-none h-48 2xl:h-40</value>
      <webElementGuid>d72a15df-6f22-4fe4-94d6-e03641f0f5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Deskripsi</value>
      <webElementGuid>4149a985-9b1d-4973-86a9-02f590298bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penambahan Data Group Oleh Katalon 05.</value>
      <webElementGuid>d1d56aed-d6f6-4171-ab45-cbf301e6503a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tmldatagroupdescription&quot;)</value>
      <webElementGuid>77f3cef6-2719-4c62-adde-70ced6171441</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='tmldatagroupdescription']</value>
      <webElementGuid>e1dc995a-b524-4c4c-adbb-60045428f54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/textarea</value>
      <webElementGuid>b19109d5-9d57-4108-8a54-d4fe97dfabac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi'])[1]/following::textarea[1]</value>
      <webElementGuid>8cd29b91-318c-480d-8897-f10dba6cf1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group ID'])[1]/following::textarea[1]</value>
      <webElementGuid>2658c36b-d54d-477f-9a29-a06c3af5ae5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dibuat'])[1]/preceding::textarea[1]</value>
      <webElementGuid>2131cb51-3a18-4e57-90be-16aa9601d8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diubah'])[1]/preceding::textarea[1]</value>
      <webElementGuid>34ab6cf2-00df-4b80-af1c-aa75fff0a638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Penambahan Data Group Oleh Katalon 05.']/parent::*</value>
      <webElementGuid>93355cf6-a9d3-4a2d-9a4a-e3f5e3957a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a03fda27-0a4a-40cf-81b5-6fafc27dc142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'tmldatagroupdescription' and @name = 'dataGroupDescription' and @placeholder = 'Tulis Deskripsi' and (text() = 'Penambahan Data Group Oleh Katalon 05.' or . = 'Penambahan Data Group Oleh Katalon 05.')]</value>
      <webElementGuid>b8a1b07a-6031-40d5-8f3a-7f715db58c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
