<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnYa</name>
   <tag></tag>
   <elementGuidId>d7111de4-0863-4a57-9227-f1b84d4b53a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnyes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnyes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8543298c-b1f0-45a6-af3f-6879b572c63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9d8059b-b3e1-4d25-a9be-10651b180e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnyes</value>
      <webElementGuid>5bb6bc0f-cf17-450b-97f6-6c24f0742e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded focus:outline-none py-2 ml-3 bg-lightblue text-white border border-lightblue w-28</value>
      <webElementGuid>7a172f8d-4c23-442c-a03b-97a64ff66204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>a8917084-23a8-466a-9cb4-1109fa615471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnyes&quot;)</value>
      <webElementGuid>0fe4ce4c-75c2-4378-9f31-4fcf24c921b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnyes']</value>
      <webElementGuid>7ad147df-6055-4004-9ab8-271bf01a8e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div[2]/div/div/div[4]/button[2]</value>
      <webElementGuid>a12edc06-468d-4384-be6e-fb460ab12077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/following::button[1]</value>
      <webElementGuid>f5326d24-d9d7-4309-9ece-038c8db6e34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CS Cslevel Dua sudah berada dalam range tanggal berikut, Apakah yakin menyimpan shift?'])[1]/following::button[2]</value>
      <webElementGuid>ac94cb9a-f5f4-45a6-8bdf-e0dae9e69d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::button[1]</value>
      <webElementGuid>ce7f4077-fde2-46b5-8116-f1ea3cf21caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[2]</value>
      <webElementGuid>b490d483-0d1a-45ae-9c67-bb26ba41391f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ya']/parent::*</value>
      <webElementGuid>8ee4cf98-9b3b-46d2-9787-76d31b4e21bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>d2c7d095-be88-4773-9809-9205ab300442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnyes' and (text() = 'Ya' or . = 'Ya')]</value>
      <webElementGuid>be6bd86b-d4e5-4102-b879-4e73fe3b1a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
