<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CloseDropDown</name>
   <tag></tag>
   <elementGuidId>e1e8be83-ef01-40b1-9023-a948b170d3f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.topbar.shadow-md.flex.justify-between.items-center.px-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef801e2c-525f-4252-aed7-3b86ab757880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>topbar shadow-md flex justify-between items-center px-10</value>
      <webElementGuid>db9bfbac-fc92-4591-8c34-5ce23e6e1323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14 Juli 2023 | 10:35super adminAdmin NexCareNotifikasiTidak ada notifikasiLihat Semua </value>
      <webElementGuid>fe84fe42-4906-42dc-8713-c97b8111c6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;topbar shadow-md flex justify-between items-center px-10&quot;]</value>
      <webElementGuid>51441aea-ca38-405e-bf80-ebc0a0319a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div</value>
      <webElementGuid>4b70d6ab-8f15-48da-80d7-5dca30678e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>f92b1413-451f-4fe7-a809-979cd1074e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '14 Juli 2023 | 10:35super adminAdmin NexCareNotifikasiTidak ada notifikasiLihat Semua ' or . = '14 Juli 2023 | 10:35super adminAdmin NexCareNotifikasiTidak ada notifikasiLihat Semua ')]</value>
      <webElementGuid>3dcbf542-6383-48ff-ba76-0ee11f07b7dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
