<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PeriodeEnd</name>
   <tag></tag>
   <elementGuidId>f503f20f-a76e-4fd3-88f2-3163250a86de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpldaterange']/div/div/div[2]/div/div[3]/div/div[contains(@aria-label,'${periodeEnd}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
