<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PeriodeStart</name>
   <tag></tag>
   <elementGuidId>53d1587a-8f4f-423e-ba2a-ea1ccc6bd890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dpldaterange']/div/div/div[2]/div/div[3]/div/div[contains(@aria-label,'${periodeStart}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
