<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bulan</name>
   <tag></tag>
   <elementGuidId>a3b5c3a2-92eb-4695-acb3-fa16cb5bcfea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ddlmonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlmonth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94a947be-2b7a-4e87-9a79-8c539c01f002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlmonth</value>
      <webElementGuid>5ba1ee1c-d444-4e58-9831-e4356811bfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between bg-white h-10 p-2 rounded shadow-box-button cursor-pointer</value>
      <webElementGuid>6704b8f2-6d87-4f2b-b543-191c26d5efd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Bulan </value>
      <webElementGuid>321d19e7-8597-4a2f-95d1-b6c7bd39ac3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlmonth&quot;)</value>
      <webElementGuid>1f4b541d-535b-45aa-81d4-ed8bbf24d9f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ddlmonth']</value>
      <webElementGuid>cf3520b0-0e65-40df-b444-54a380fdae4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div[4]/div/div</value>
      <webElementGuid>07e1f10c-1a92-404a-ac02-e826d087ed44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode'])[1]/following::div[3]</value>
      <webElementGuid>45fb8a0b-9cb5-403a-a41e-27600ae5154e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/following::div[6]</value>
      <webElementGuid>5b95c475-296c-436f-bfa5-663e953f3bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Januari'])[1]/preceding::div[3]</value>
      <webElementGuid>778f124f-459e-4b64-ba0d-8650f3165bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div</value>
      <webElementGuid>76cdeac3-0d9b-41e1-912d-05b053397739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ddlmonth' and (text() = ' Bulan ' or . = ' Bulan ')]</value>
      <webElementGuid>3a5ad87a-3f5b-4309-b2ac-fd0284f82926</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
