<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Periode</name>
   <tag></tag>
   <elementGuidId>6fa7f6dd-6fd6-4e83-b4f6-abdf04c61fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnperiode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnperiode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82f7d3e3-e4d6-46dc-b20b-de494fb8a1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnperiode</value>
      <webElementGuid>96129b36-31da-41e6-8eab-1ac3958dcf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between items-center cursor-pointer p-2</value>
      <webElementGuid>ba9acd0c-0476-4180-96cf-33d0189eeed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Periode </value>
      <webElementGuid>dfe28cff-5e0b-4b59-aedc-354280d27f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnperiode&quot;)</value>
      <webElementGuid>df89c327-99ed-4ebf-a623-c55eabbd0e80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnperiode']</value>
      <webElementGuid>3f9f437d-905a-440f-90b4-fbda58965d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div[3]</value>
      <webElementGuid>d0f20c74-acd0-4c8b-bc92-c818b255d816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/following::div[2]</value>
      <webElementGuid>d1984312-745b-4489-a8fe-36bb8553cfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Nexcare'])[1]/following::div[3]</value>
      <webElementGuid>061276ff-a639-400b-b0f1-d9cf8ea0d5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[3]</value>
      <webElementGuid>67a7dc1f-f480-4b2b-8ccf-56ac8e4c747b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btnperiode' and (text() = ' Periode ' or . = ' Periode ')]</value>
      <webElementGuid>ae8a5d08-4677-481e-ab34-a4d0c4c5e35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
