<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IInsert</name>
   <tag></tag>
   <elementGuidId>5f4d0e9d-a10d-47cc-a100-d01fd47500de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ckbimportdatainsert</value>
      <webElementGuid>871f0fda-943a-40b4-b0d1-280c693163e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
