<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ya</name>
   <tag></tag>
   <elementGuidId>66df6888-4080-4a59-86bd-36ad8f9169e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[3]/div[1]/div[2]/div[2]/div[3]/div[1]/div/div[4]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ffaaf1f-c210-4208-9693-6f07ac53b9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8d808af-33ad-4fce-8f74-7d26f08c9ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-lightblue rounded text-white border border-lightblue focus:outline-none w-28 py-2 ml-3</value>
      <webElementGuid>47a071ee-ff1e-4e57-a4d8-8f55a67af0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>05c349a8-85c0-40ea-a71b-7e1d84ef2710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;h-1/5 flex justify-between items-center&quot;]/div[@class=&quot;date-time-notification flex items-center&quot;]/div[@class=&quot;flex&quot;]/div[3]/div[@class=&quot;transition duration-300 flex justify-center items-center fixed inset-0 outline-none focus:outline-none opacity-1 transform scale-100&quot;]/div[@class=&quot;border-0 rounded-2xl shadow bg-white outline-none focus:outline-none p-10 text-center text-gray-600 alert-box&quot;]/div[@class=&quot;block&quot;]/button[@class=&quot;bg-lightblue rounded text-white border border-lightblue focus:outline-none w-28 py-2 ml-3&quot;]</value>
      <webElementGuid>62ee15c4-8260-448a-b4d6-6fe3dff80cdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>42c6b365-ce32-4f94-973d-d4952f9914be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div[2]/div[3]/div/div/div[4]/button[2]</value>
      <webElementGuid>4a76dfe8-9863-4350-b1ca-52a9ecab1551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/following::button[1]</value>
      <webElementGuid>d76a55fb-d96f-4c4b-ba28-bf3a79055d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda yakin keluar dari aplikasi NexCare?'])[1]/following::button[2]</value>
      <webElementGuid>c1e01b01-0966-4635-ac0a-d1328740e5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::button[1]</value>
      <webElementGuid>337f9ffa-9bb6-43c1-8ec7-f91600bd046a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atur Ulang'])[1]/preceding::button[3]</value>
      <webElementGuid>c511e1a3-fc89-47c1-b182-5a6a44bed7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ya']/parent::*</value>
      <webElementGuid>723d2a7e-3235-4597-8438-9594f75ab18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>45b1015f-0b70-4e53-84ef-fc3486e74f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ya' or . = 'Ya')]</value>
      <webElementGuid>8cb64501-16b9-4c49-85fd-fe6dd94ee9ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
