<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tambah</name>
   <tag></tag>
   <elementGuidId>c7c47542-3fd2-4f2e-ab67-5442aeaac44b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div[3]/div/div[7]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cursor-pointer.bg-darkblue.rounded-full.text-white.text-center.font-bold.w-full.px-2.py-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52be37cd-1e23-4164-9288-70aa4cf5724b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer bg-darkblue rounded-full text-white text-center font-bold w-full px-2 py-1</value>
      <webElementGuid>303b9370-2cc7-49fd-96a0-3b48f518f5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>f5a4a122-da86-4526-9e72-8941d84ebea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;flex text-gray-600 white-container&quot;]/div[@class=&quot;w-full bg-white rounded-lg p-5 relative&quot;]/div[@class=&quot;bg-white mb-40 shadow-lg relative&quot;]/div[@class=&quot;pt-5 px-10 bg-blue-100 absolute top-full w-full shadow-lg rounded-b-xl&quot;]/div[@class=&quot;pb-5 px-5 text-gray-700 flex justify-between&quot;]/div[@class=&quot;w-40&quot;]/div[@class=&quot;cursor-pointer bg-darkblue rounded-full text-white text-center font-bold w-full px-2 py-1&quot;]</value>
      <webElementGuid>97ac454f-d151-4748-aea3-1b375ebc6e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div[3]/div/div[7]/div</value>
      <webElementGuid>ffd19843-0c1e-4db3-93e1-c3e6ed7cfcc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::div[7]</value>
      <webElementGuid>80d07b5b-4839-4464-977b-cc6490e0740d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Principal'])[1]/following::div[21]</value>
      <webElementGuid>487672c3-e7a6-4e2d-9ba8-9746cdb6cc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::div[1]</value>
      <webElementGuid>3914c566-1b8b-4965-8039-e0fda4225d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::div[1]</value>
      <webElementGuid>ef55bc89-8cf2-4319-8c0a-7c1c154b0b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah']/parent::*</value>
      <webElementGuid>9cd310ec-d4d2-4f81-9e9c-540c0db2d7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[7]/div</value>
      <webElementGuid>b999b787-91dc-49f5-a989-b958fabffc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>abcf49f9-767c-4b05-b965-ec148bbb3cef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
