<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MASTER DATA</name>
   <tag></tag>
   <elementGuidId>8cbd5366-b0e1-4d4d-9490-e333c75138b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div[2]/div[6]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b3a9128-2ce8-4e71-8a56-61ee28029ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-5 flex justify-between items-center w-4/5</value>
      <webElementGuid>03dfdff0-2c4b-4120-98e2-1e1ff27f592a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MASTER DATA</value>
      <webElementGuid>218a1ecb-f09c-4eb2-8768-4ab57f45e1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[2]/div[@class=&quot;sidebar&quot;]/div[@class=&quot;body h-4/6 overflow-auto&quot;]/div[@class=&quot;my-3&quot;]/div[@class=&quot;py-3 px-10 flex items-center select-none&quot;]/div[@class=&quot;ml-5 flex justify-between items-center w-4/5&quot;]</value>
      <webElementGuid>ad1330ac-47fc-46e7-acf7-0c2e84f164ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div[2]/div[6]/div/div[2]</value>
      <webElementGuid>bc355177-4605-4935-9001-abdf60915a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SESSION'])[1]/following::div[4]</value>
      <webElementGuid>4cc503d5-4d0d-475b-94e1-035daf317767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANTRIAN'])[1]/following::div[4]</value>
      <webElementGuid>71ef0415-db40-4968-91f3-059935998d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA GROUP'])[1]/preceding::div[1]</value>
      <webElementGuid>814f0ba7-15db-41a1-b3be-fbb1e9617c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]</value>
      <webElementGuid>b87de4bb-31ae-4987-bbbc-d6749beeb0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MASTER DATA' or . = 'MASTER DATA')]</value>
      <webElementGuid>56a3df8e-0c30-4ffa-97d3-9b973375cd3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
