<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilih Principal_branchId</name>
   <tag></tag>
   <elementGuidId>bc256d82-868c-461b-b701-94537a378d84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='branchId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;branchId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40df3c03-4c07-4832-9c78-697be5446fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90b2ffbc-8205-4d65-9ca2-4b3d3dbbd21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b75dfb03-d924-4eca-b440-3bd3336e666c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branchId</value>
      <webElementGuid>fceaed55-76be-4ead-9a5a-9ef24abd0870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Cabang</value>
      <webElementGuid>5580c5c9-52c8-4435-b16d-cd6008a56d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;flex text-gray-600 white-container&quot;]/div[@class=&quot;w-full bg-white rounded-lg p-5 relative&quot;]/div[@class=&quot;bg-white mb-40 shadow-lg relative&quot;]/div[@class=&quot;pt-5 px-10 bg-blue-100 absolute top-full w-full shadow-lg rounded-b-xl&quot;]/div[@class=&quot;pb-5 px-5 text-gray-700 flex justify-between&quot;]/div[@class=&quot;w-40&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>df18d66f-1f27-4aa1-864b-8da42a427690</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='branchId']</value>
      <webElementGuid>2bd4dcd2-20c6-4e88-86c9-7fa27d7861a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div[3]/div/div[3]/input</value>
      <webElementGuid>2955d2fb-6853-4d16-8318-3989bd7be8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>ced3795c-4e82-49fa-ac81-91d601882270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'branchId' and @placeholder = 'Kode Cabang']</value>
      <webElementGuid>fd79492f-e811-4d3c-956b-cdafc02772be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
