<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilih Principal_nsCode</name>
   <tag></tag>
   <elementGuidId>abcc8089-4981-4f3a-87bf-dee315d0d1ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nsCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nsCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0e371ce-93db-47d7-81ca-76caf6b79033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bda2949e-3e50-4483-944d-d3caaf4bab7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bbf03d26-ebc9-468e-83b9-0e803bc6b20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nsCode</value>
      <webElementGuid>fdabe906-f622-4859-a0e7-5eca7683300b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Pelanggan</value>
      <webElementGuid>1d073add-936c-4450-9b4e-5f5752863515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;flex text-gray-600 white-container&quot;]/div[@class=&quot;w-full bg-white rounded-lg p-5 relative&quot;]/div[@class=&quot;bg-white mb-40 shadow-lg relative&quot;]/div[@class=&quot;pt-5 px-10 bg-blue-100 absolute top-full w-full shadow-lg rounded-b-xl&quot;]/div[@class=&quot;pb-5 px-5 text-gray-700 flex justify-between&quot;]/div[@class=&quot;w-48&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>7f3fe6df-e032-473a-86b4-84017f027287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nsCode']</value>
      <webElementGuid>da7f4224-d9ec-4940-8c67-d78a393fc33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>355e7963-5aa9-4904-a707-83c66147380d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8a9d0aa3-1f82-45cd-bc8e-b610449f9c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nsCode' and @placeholder = 'Kode Pelanggan']</value>
      <webElementGuid>92a0c80e-e6bd-49b8-9558-03a4fe9770d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
