<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilih Principal_distributorCode</name>
   <tag></tag>
   <elementGuidId>29d960e7-0b7e-421e-bd84-eaa8e8595357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='distributorCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;distributorCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d41a9e8-f5f8-4153-b6fa-ae9a07ff9abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38e0af34-f1cd-47b7-8796-70ec1597d0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7a9f3208-b133-4946-8e74-dfcff6d14b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>distributorCode</value>
      <webElementGuid>fb927b76-e5af-4354-8cf1-7954a239ed11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Distributor</value>
      <webElementGuid>cc6940df-a6d8-490b-bf24-7b7c6ea65787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;flex text-gray-600 white-container&quot;]/div[@class=&quot;w-full bg-white rounded-lg p-5 relative&quot;]/div[@class=&quot;bg-white mb-40 shadow-lg relative&quot;]/div[@class=&quot;pt-5 px-10 bg-blue-100 absolute top-full w-full shadow-lg rounded-b-xl&quot;]/div[@class=&quot;pb-5 px-5 text-gray-700 flex justify-between&quot;]/div[@class=&quot;w-32&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>66a9533d-bae5-4741-92dc-53d16ef3ff88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='distributorCode']</value>
      <webElementGuid>f2b11377-013e-4445-a6fa-814c267e939c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/div[2]/div[3]/div/div[5]/input</value>
      <webElementGuid>a2e62d30-09c9-47da-aa45-bd9ff22885ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>0a0c208e-8cc3-49a7-a833-7dc176c01b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'distributorCode' and @placeholder = 'Kode Distributor']</value>
      <webElementGuid>e397f607-1602-49dd-8fe5-879bad20e834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
