<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filter</name>
   <tag></tag>
   <elementGuidId>6ea2ca4a-96f6-4f41-b71a-0104ee7eebc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.justify-between.items-center.bg-white.h-10.p-2.rounded.shadow-box-button.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ee60456-77db-441c-866a-949b2d22b2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between items-center bg-white h-10 p-2 rounded shadow-box-button cursor-pointer</value>
      <webElementGuid>9f582672-56ed-4a0a-9d2d-e72b921299fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>7119e38d-626c-40b2-ac9c-846593c74e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;flex justify-between pb-10&quot;]/div[@class=&quot;flex-initial w-3/12&quot;]/div[@class=&quot;relative font-medium select-none&quot;]/div[@class=&quot;flex justify-between items-center bg-white h-10 p-2 rounded shadow-box-button cursor-pointer&quot;]</value>
      <webElementGuid>73c227af-8d16-4c7d-ac8f-db1a53079475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div</value>
      <webElementGuid>2b0bf1d3-37c0-45be-8b22-9cb1ea1383e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Officer'])[1]/following::div[5]</value>
      <webElementGuid>3298a9b1-6857-4545-af55-53bfda8d8d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead'])[1]/following::div[6]</value>
      <webElementGuid>6838083e-736d-48ea-a26a-96c1f7cac044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama CS'])[1]/preceding::div[2]</value>
      <webElementGuid>c3557cdf-b5b0-49cf-85e2-7b86171c4c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div</value>
      <webElementGuid>2d406b3d-e598-4bae-bb40-90dd2ef7319f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>d2fe4fb2-3a02-49b2-a24a-3652c540f855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
