<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tahun</name>
   <tag></tag>
   <elementGuidId>edb6d252-3c2e-46b6-8933-c4fb4c4b6848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ddlyear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlyear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>21d70616-49c1-4e92-8cea-a1df103224de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlyear</value>
      <webElementGuid>17ed8e20-b06a-4b8d-92e9-cc4833d047ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between bg-white h-10 p-2 rounded shadow-box-button cursor-pointer</value>
      <webElementGuid>f8c4882e-5336-41fe-ae93-6fbdf5917965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tahun </value>
      <webElementGuid>5bb829d5-0ca7-4b10-b27a-2b9c3bc7957b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlyear&quot;)</value>
      <webElementGuid>08d28157-b2dd-46d6-aee5-9218cd421fb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ddlyear']</value>
      <webElementGuid>6bc92c91-cb5b-4952-a8f5-e92a11195b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div[4]/div[2]/div</value>
      <webElementGuid>6e131eec-7af9-4156-8960-a23712411512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desember'])[1]/following::div[2]</value>
      <webElementGuid>166ea256-ecea-488d-a86a-f3bcd9c2e855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='November'])[1]/following::div[3]</value>
      <webElementGuid>199857c9-5c7e-4065-bf4d-4e0fd1bb896a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::div[15]</value>
      <webElementGuid>32723479-1d1d-41a0-82f5-99bd156b816a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div[2]/div</value>
      <webElementGuid>a90c8a06-1e67-4515-a929-c39f1c0432ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ddlyear' and (text() = ' Tahun ' or . = ' Tahun ')]</value>
      <webElementGuid>464945b3-ebde-42a4-b884-61473dd8b57c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
