<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msgValidation</name>
   <tag></tag>
   <elementGuidId>51cdcc56-87ed-492d-a83c-56b8ac15ff26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-2xl.font-medium.whitespace-normal.mb-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[3]/div/div/div[4]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9f2ab8d-5a72-4f3d-b404-f313f3f597ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-2xl font-medium whitespace-normal mb-3</value>
      <webElementGuid>9a297f1c-f12c-4112-81bd-557b7b076b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data principal_id 0 tidak diketahui</value>
      <webElementGuid>f994e069-d789-4702-a2dc-436974ab6d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;flex text-gray-600 white-container calculate-layout&quot;]/div[@class=&quot;w-full bg-white rounded-lg p-5 relative&quot;]/div[4]/div[@class=&quot;transition duration-300 flex justify-center items-center fixed inset-0 outline-none focus:outline-none opacity-1 transform scale-100&quot;]/div[@class=&quot;border-0 rounded-2xl shadow bg-white outline-none focus:outline-none p-10 text-center text-gray-600 alert-box&quot;]/div[@class=&quot;text-2xl font-medium whitespace-normal mb-3&quot;]</value>
      <webElementGuid>5c24fe6b-2ed0-46c6-bf29-2af58a645f53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div[4]/div/div/div[2]</value>
      <webElementGuid>cfa03127-c1d2-4186-80e4-5c0e0c5d9f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/following::div[6]</value>
      <webElementGuid>46427aac-b284-45d3-97f9-fda500682d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::div[6]</value>
      <webElementGuid>e75478f3-aa9b-4b09-a1bc-1de60767f051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/preceding::div[2]</value>
      <webElementGuid>d6373040-f33d-42da-85db-701e11d5c720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[1]/preceding::div[2]</value>
      <webElementGuid>72a04365-734e-4879-a053-1b4cae81f8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Data principal_id 0 tidak diketahui']/parent::*</value>
      <webElementGuid>767d3f73-239e-439e-aa4d-6f2b9db20933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/div/div/div[2]</value>
      <webElementGuid>be490e2d-5f01-48b8-be70-90c41045fd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Data principal_id 0 tidak diketahui' or . = 'Data principal_id 0 tidak diketahui')]</value>
      <webElementGuid>83640135-ac9d-4a64-af5e-6dcf4161f064</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
