<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Periode</name>
   <tag></tag>
   <elementGuidId>ab0867f3-b811-421b-a9e1-457a9eeffc17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnperiode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnperiode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47271537-c764-4e4e-b449-aa76db2ae4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnperiode</value>
      <webElementGuid>66acb7a6-f503-4e16-bcc7-e552d59382f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between items-center cursor-pointer p-2</value>
      <webElementGuid>f314fccb-feee-4fd4-971a-1e7abb905de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Periode </value>
      <webElementGuid>1ab83a4d-175a-4898-bd81-373488604d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnperiode&quot;)</value>
      <webElementGuid>48f25366-03bf-461f-af8a-4bba273fd1e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnperiode']</value>
      <webElementGuid>c0ead10f-5686-49dd-92cb-3c675a04ffa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div[3]</value>
      <webElementGuid>5fd74cce-0e08-4c47-a73f-f66ec9bfbc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/following::div[2]</value>
      <webElementGuid>446ab822-e80c-434c-86cb-9768b39f08ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Nexcare'])[1]/following::div[3]</value>
      <webElementGuid>b3fe02be-e33f-497a-b000-1f340aa48ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[3]</value>
      <webElementGuid>4399859c-2025-45f3-bbc6-c10c2e2f0d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btnperiode' and (text() = ' Periode ' or . = ' Periode ')]</value>
      <webElementGuid>afe78b41-8116-4824-ba81-f55c20b054de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
