<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cslevel Dua</name>
   <tag></tag>
   <elementGuidId>065f6bef-4ce8-4316-9c6f-bf81993c7b5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b408cc8-936d-4557-a428-be8fa995f1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1n7v3ny-option</value>
      <webElementGuid>735afaab-3f66-4a14-a2cc-e772403d5fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-21</value>
      <webElementGuid>f45b22de-0a6a-4a64-9192-7642336c6c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1603586a-84db-467d-9e3b-71d5673d4779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cslevel Dua</value>
      <webElementGuid>c393abeb-09f1-4974-96eb-82acc16fb469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-21&quot;)</value>
      <webElementGuid>ad62b3d1-40ca-465e-bad4-4076c5195b37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-21']</value>
      <webElementGuid>6f24b1b0-2120-47ea-809f-31ba01e765c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div[2]/div/div/div[2]/div/div[22]</value>
      <webElementGuid>ba1d97c3-aedf-43f9-afc1-026aa2ef7a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cslevel Satu'])[1]/following::div[1]</value>
      <webElementGuid>66aee0e6-137b-436e-a558-475cc3ac3b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riyandi Natapunta'])[1]/following::div[2]</value>
      <webElementGuid>2ba43e26-6268-4504-8b28-511f2402d54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cs Officer'])[1]/preceding::div[1]</value>
      <webElementGuid>f91d4e7c-af06-41dd-a65d-c8af0f3209d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jansen Cs'])[1]/preceding::div[2]</value>
      <webElementGuid>876cb3e6-7c20-4fdb-9215-57ebc1497fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cslevel Dua']/parent::*</value>
      <webElementGuid>c852bde9-4692-410d-8296-8e560f07f484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]</value>
      <webElementGuid>6391981a-889d-45ff-a2d8-8bf7ab2e03fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-21' and (text() = 'Cslevel Dua' or . = 'Cslevel Dua')]</value>
      <webElementGuid>eb40e91c-54cf-4bc6-b069-b3032f10e84f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
