<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Agustus</name>
   <tag></tag>
   <elementGuidId>da7a2aae-8d41-4f62-b773-72587b2ff5fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div[4]/div/div[2]/div[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73bcaccc-0c0b-4174-9eb9-66056ed010e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:bg-blue-100 px-3 py-1 cursor-pointer</value>
      <webElementGuid>31dd3ca0-2df1-4bc0-98cc-cab14588decb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agustus</value>
      <webElementGuid>dc831611-05a5-49ac-8352-13c366885bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;flex justify-between pb-10&quot;]/div[@class=&quot;flex-initial w-3/12&quot;]/div[@class=&quot;relative font-medium select-none&quot;]/div[@class=&quot;absolute w-full top-14 bg-white z-10 pb-6 rounded shadow-box-button&quot;]/div[@class=&quot;bg-blue-200 w-full p-2 flex&quot;]/div[@class=&quot;w-1/2 pr-1&quot;]/div[@class=&quot;mt-2 bg-white rounded shadow-box-button overflow-auto h-40&quot;]/div[@class=&quot;hover:bg-blue-100 px-3 py-1 cursor-pointer&quot;]</value>
      <webElementGuid>3d9f6936-e9ea-40f7-8dc6-a278dd951b89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div[4]/div/div[2]/div[8]</value>
      <webElementGuid>e4323e2f-9778-4dd8-8017-f0e6127ccaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Juli'])[1]/following::div[1]</value>
      <webElementGuid>885ecef8-dfd0-4a20-98d4-48f6858ce658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Juni'])[1]/following::div[2]</value>
      <webElementGuid>f85ff202-4ae0-4fec-885f-e31f65f954b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='September'])[1]/preceding::div[1]</value>
      <webElementGuid>517a02e3-df64-4838-b428-c14a80e329cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oktober'])[1]/preceding::div[2]</value>
      <webElementGuid>75c4a4ca-fa6e-41de-ba1a-9308ab723bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agustus']/parent::*</value>
      <webElementGuid>6e0b6de6-1b87-444b-b19a-946643b55e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[8]</value>
      <webElementGuid>368d5f4b-4009-4dfa-8000-5bf816225689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Agustus' or . = 'Agustus')]</value>
      <webElementGuid>92eda3cb-7644-4920-b95c-c819feb6bf12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
