<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nama CS</name>
   <tag></tag>
   <elementGuidId>69024904-c461-46de-a2ed-c5b6ff57f1dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ddscsname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ddscsname']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ddscsname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a4fd458-e3ec-4770-92b5-a7cb6525f83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddscsname</value>
      <webElementGuid>2e3fcf5c-7668-4baf-b783-30d163981a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between items-center cursor-pointer p-2</value>
      <webElementGuid>3612fbc9-3833-4de6-97b9-0870d8c2f66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Nama CS </value>
      <webElementGuid>31fb4ff9-7df4-48c0-b07a-28f2a350bae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddscsname&quot;)</value>
      <webElementGuid>f4265425-c2da-4faf-8989-4640ec308320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ddscsname']</value>
      <webElementGuid>f087b437-c56c-4372-b325-c9f0eb56f204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>f67b3df0-8575-4fff-9f51-b4cc8d880eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::div[2]</value>
      <webElementGuid>5eccd173-6e63-414a-ada9-42a59f23b37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Officer'])[1]/following::div[8]</value>
      <webElementGuid>076b95b2-5259-41ab-bd93-5e3270f5277d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Nama CS'])[1]/preceding::div[2]</value>
      <webElementGuid>a18e73d5-b0ef-41db-823c-dd5bdac6f14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>e3581e1a-4816-4073-8816-bc3a35f5084e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ddscsname' and (text() = ' Nama CS ' or . = ' Nama CS ')]</value>
      <webElementGuid>e21742ca-dcb1-44e4-9150-7d4447f34b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
