<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bulan</name>
   <tag></tag>
   <elementGuidId>b28f96a1-286e-4da4-b8b8-03b901f69e38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ddlmonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlmonth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7947ab3d-603a-4296-9175-953beff7686c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlmonth</value>
      <webElementGuid>b49c6d5c-aa42-41aa-8295-aa64997013da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between bg-white h-10 p-2 rounded shadow-box-button cursor-pointer</value>
      <webElementGuid>678d51ca-4547-4096-a702-1d411000a956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Bulan </value>
      <webElementGuid>74b4a737-a971-45d4-a571-d2fd8f5d016d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlmonth&quot;)</value>
      <webElementGuid>6101ec96-d5f8-4394-b1a6-9e1d7a9dee86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ddlmonth']</value>
      <webElementGuid>688826ac-5e64-40cd-9057-dc7c16569a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div[4]/div/div</value>
      <webElementGuid>542c9347-3540-47af-9a28-89686b9b80b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode'])[1]/following::div[3]</value>
      <webElementGuid>d511764a-1ac2-4a81-b98d-c2b69359ab4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/following::div[6]</value>
      <webElementGuid>7a0d9b73-c7c4-455c-82e0-98bab9d04bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Januari'])[1]/preceding::div[3]</value>
      <webElementGuid>04905341-a0fc-46b7-9398-c2d3716e124e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div</value>
      <webElementGuid>ea68d1ef-3dd9-4a66-8519-1e604cf6ca70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ddlmonth' and (text() = ' Bulan ' or . = ' Bulan ')]</value>
      <webElementGuid>701428f0-e263-4d14-b94f-78a22bcebea3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
