<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__maxPoint</name>
   <tag></tag>
   <elementGuidId>17083c55-97ac-4eee-bb75-e80c155b126c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tslpointmax</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tslpointmax']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47b0a995-4bf2-4ad6-b3c6-0204aa8e3049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslpointmax</value>
      <webElementGuid>9fbd8800-79bf-4f0e-988d-ba9b6c4c365a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b282b588-69eb-40ef-a759-f4a6cd81beeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxPoint</value>
      <webElementGuid>687232de-965e-45d9-9152-5a6fbe0eec42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-second w-full false</value>
      <webElementGuid>b5a0694f-0524-4f80-88f5-fb0289630e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d4b3c0e6-972c-4378-8da0-1217467264ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>aee52d59-ec8d-44cb-b559-768e3880e24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;white-container pb-5&quot;]/div[@class=&quot;w-full bg-white border border-gray-300 rounded-lg p-8 pb-10 space-y-10&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;space-y-5&quot;]/div[@class=&quot;flex w-full
                                            false&quot;]/div[@class=&quot;flex w-full items-center space-x-10&quot;]/div[@class=&quot;w-2/12 relative&quot;]/input[@id=&quot;tslpointmax&quot;]</value>
      <webElementGuid>1aa5810f-3344-4efa-b58e-47e22700adc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tslpointmax']</value>
      <webElementGuid>52ce3b2b-aa8f-4235-a3f6-f117c3cef6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div[3]/div/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>965f0390-8305-4338-a82f-192a5a10c8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>28436427-087e-4ccb-9091-7cb7be957399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tslpointmax' and @type = 'number' and @name = 'maxPoint' and @placeholder = '0']</value>
      <webElementGuid>ebedf41b-d2fc-4784-bc56-b06d33ee4385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
