<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimal 1_checkInfinity</name>
   <tag></tag>
   <elementGuidId>de71f733-c474-464b-bd86-2dff0e09b051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ckbinfinite'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f830332-2c9d-47b8-a5d8-66f122f28390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ckbinfinite</value>
      <webElementGuid>60c3b6cd-c6f4-4a3e-adb2-05b1f0e9735d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fbcf3847-08a3-4d6c-be05-8596bc7d6001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkInfinity</value>
      <webElementGuid>c66d7bec-31b3-4618-8e2e-6313fcc2add6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-6 w-6 border</value>
      <webElementGuid>f6f96a94-9160-4240-88ec-4714d68c9132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;white-container pb-5&quot;]/div[@class=&quot;w-full bg-white border border-gray-300 rounded-lg p-8 pb-10 space-y-10&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;space-y-5&quot;]/div[@class=&quot;flex w-full
                                            false&quot;]/div[@class=&quot;flex w-full items-center space-x-10&quot;]/div[@class=&quot;w-3/12&quot;]/div[@class=&quot;flex justify-center mt-6 space-x-3&quot;]/input[@id=&quot;ckbinfinite&quot;]</value>
      <webElementGuid>99ebd800-e111-4ca8-985a-60ade4d080ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ckbinfinite'])[3]</value>
      <webElementGuid>12930ba4-b5f7-45b5-9ee4-d2f4084d3b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div[3]/div/div[2]/div[2]/div[3]/div/div[3]/div/input</value>
      <webElementGuid>3690b6af-cd39-438b-bd04-072288caf6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/input</value>
      <webElementGuid>e28222b1-1f15-4eee-a2b5-005dcbbc1e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ckbinfinite' and @type = 'checkbox' and @name = 'checkInfinity']</value>
      <webElementGuid>d189686e-8ecd-4693-bb2a-d58fd0f0881a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
