<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__complaintSub</name>
   <tag></tag>
   <elementGuidId>b2f32e3d-e749-4d23-ac74-fd697fba2365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='tslcategory'])[22]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26d985ab-f676-46a5-ba4a-be9278605daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslcategory</value>
      <webElementGuid>56856cbd-f87e-4fa4-acdc-4d02ff4559da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fc46afc-cdfb-4473-805b-bebcd90219dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>complaintSub</value>
      <webElementGuid>61b67e86-e4f1-4113-89c2-8833cea0ffa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-second w-full</value>
      <webElementGuid>20b756d0-13bb-445b-9ddb-60b417c69ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kategori Keluhan</value>
      <webElementGuid>5bbf6817-599e-4218-9f4b-9f3e67fd7fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;white-container pb-5&quot;]/div[@class=&quot;w-full bg-white border border-gray-300 rounded-lg p-8 space-y-10&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;space-y-5 overflow-y-auto h-96 p-1&quot;]/div[@class=&quot;flex w-full
                                                            false
                                                            undefined&quot;]/div[@class=&quot;flex w-full justify-between items-center space-x-5&quot;]/div[@class=&quot;w-4/12&quot;]/input[@id=&quot;tslcategory&quot;]</value>
      <webElementGuid>5384b7b2-e64a-48ac-92ed-f9938b7b1090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='tslcategory'])[22]</value>
      <webElementGuid>85f80907-aa33-482e-992e-8c25b355411b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div[3]/div/div[2]/div[2]/div[22]/div/div/input</value>
      <webElementGuid>7aa08338-b2ee-49ac-bf0b-948c14a8258c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/input</value>
      <webElementGuid>d9e5c254-a28b-4aa0-8c5b-d9605fde683c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tslcategory' and @type = 'text' and @name = 'complaintSub' and @placeholder = 'Kategori Keluhan']</value>
      <webElementGuid>ed48be34-bff0-4d97-82c3-e93250c41e7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
