<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__reportMapping</name>
   <tag></tag>
   <elementGuidId>0a56ca5f-aa05-40b5-a473-293f0d41b9cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='tslreportmapping'])[22]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79661784-1fd5-4a62-a345-8b4cfd1fbd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslreportmapping</value>
      <webElementGuid>6c0e8d90-c7c7-4734-975b-5c32ec0f4a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcfc4271-3b8a-4ce8-95c4-41031b52000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reportMapping</value>
      <webElementGuid>bfb176f9-69c2-4c38-bdb7-7f085069dad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-second w-full</value>
      <webElementGuid>5c59236b-3ecb-423a-8b77-20e013e736c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Report Mapping</value>
      <webElementGuid>48465ded-cc45-4d34-b7c8-76bda9dc8cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;white-container pb-5&quot;]/div[@class=&quot;w-full bg-white border border-gray-300 rounded-lg p-8 space-y-10&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;space-y-5 overflow-y-auto h-96 p-1&quot;]/div[@class=&quot;flex w-full
                                                            false
                                                            undefined&quot;]/div[@class=&quot;flex w-full justify-between items-center space-x-5&quot;]/div[@class=&quot;w-4/12&quot;]/input[@id=&quot;tslreportmapping&quot;]</value>
      <webElementGuid>e63a1140-e4eb-4a2d-8a05-58b312aea532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='tslreportmapping'])[22]</value>
      <webElementGuid>ef78d2bf-e62d-4427-b082-efe57fe22dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div[3]/div/div[2]/div[2]/div[22]/div/div[5]/input</value>
      <webElementGuid>bf8e8f8c-0055-49bc-8f0b-fb088315cb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[5]/input</value>
      <webElementGuid>9e16bdf3-e41a-4f70-bba1-01c10309d9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tslreportmapping' and @type = 'text' and @name = 'reportMapping' and @placeholder = 'Tulis Report Mapping']</value>
      <webElementGuid>bcf1a425-1c12-4560-bed9-aaa9c3a46771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
