<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DeleteKMS</name>
   <tag></tag>
   <elementGuidId>c57f1a44-f76d-4012-8bcd-85ed3d03b9c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btndelete > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='${judul}'])[1]/following::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>c4b3238e-da58-4dbd-a159-203bdd895b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>ad37b203-dc76-42a4-9a16-ee6c82c16152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>8a04c7b7-189a-4fa7-95b0-69cec3e221b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>72a12ef6-9848-4340-bb85-bbd184b67709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>4d77218a-2068-4bb9-8174-4320eb8b32c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 28 28</value>
      <webElementGuid>5efdd9a5-48ef-4a2e-a2c2-c404475ce015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btndelete&quot;)/svg[1]</value>
      <webElementGuid>2df6e57d-63d0-4f43-bb76-a47738c6c4ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Both'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>4f24c276-6ea8-4034-8d6a-862ba7b7aed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mutasi adjust stock HA'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>577e3ac9-652d-45b9-9da2-c79ad429ac04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>c73c2538-751f-4a2c-9e63-ba58c9c3c369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>d1fe33dc-7cdf-46df-b344-713c0f50c1e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
