<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Title</name>
   <tag></tag>
   <elementGuidId>04848ed1-819b-4e93-b4f5-ae90971b4e0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tsltitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tsltitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94f29faf-1ac4-49ee-ac99-1912f2236e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tsltitle</value>
      <webElementGuid>a3190da8-4bee-4657-9557-5d09ed149ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f17d957-f65f-44c4-b38e-c2291a88bf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>ed5b020f-5648-48f9-8daa-a98566252350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Judul</value>
      <webElementGuid>6139c417-b8d1-4f37-9e89-abbf349560e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-full</value>
      <webElementGuid>8a2e4e2f-cc13-4374-9983-8cc01d354c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>45d884d1-1f6a-4922-a0ad-3f061fcde2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>78513870-8e2d-4974-80f9-131a35cbecdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tsltitle&quot;)</value>
      <webElementGuid>8ad3f457-b5eb-43c3-89d4-3f78c575d6e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tsltitle']</value>
      <webElementGuid>2fec8424-ac18-4c64-92b8-043be64231d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>a1067c7b-528c-4767-b7f9-1b85cfd7df49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>39773aac-00f6-4702-944f-8100c99834f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tsltitle' and @type = 'text' and @name = 'title' and @placeholder = 'Tulis Judul']</value>
      <webElementGuid>67b85e78-aa43-4cd5-ac82-00a47d70e99e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
