<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link</name>
   <tag></tag>
   <elementGuidId>50bbf014-3f13-4592-924f-af24bac13f1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tslurllink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tslurllink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e56830c-0f1c-4703-95f2-466227905d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslurllink</value>
      <webElementGuid>5266afc0-fb34-493d-9044-07362d2b19ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a89d542b-f4e4-4705-a1dc-bed301b9eb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>urlLink</value>
      <webElementGuid>8fb0762b-5628-4f06-b400-6d0817bd4032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Link Url</value>
      <webElementGuid>c0a32a54-9c94-40e4-ab74-2b89709bfd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-full</value>
      <webElementGuid>d23dbabb-e4c3-45bc-a446-342333b7ebdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>e62c8850-196c-45f4-a29b-8c40bc247b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tslurllink&quot;)</value>
      <webElementGuid>0e2d3edf-ed9d-4726-8ca4-c73ea69d1784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tslurllink']</value>
      <webElementGuid>efdf9185-bdd0-49c4-af01-6a77bf8fc19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>ee904c39-d0fd-4846-9560-b8df9d183abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a359adf7-2b27-4c3e-aec5-9655e61e8629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tslurllink' and @type = 'text' and @name = 'urlLink' and @placeholder = 'Tulis Link Url']</value>
      <webElementGuid>c788c719-bb0e-481b-901a-793dda816fb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
