<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Description</name>
   <tag></tag>
   <elementGuidId>1f973836-75df-4633-bee8-d815da6d0524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tsldescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='tsldescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>139ba615-e97f-48df-8c9c-1daef2eef5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tsldescription</value>
      <webElementGuid>d52a79a8-0edc-4d58-80ac-5260b2b256ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c639608e-8683-4aa5-87b7-ca5d55701bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>aeddb8f4-0ad5-4613-8b57-c3209d11de3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Deskripsi</value>
      <webElementGuid>eb38a430-98fb-4b50-9619-fd5e20959721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-full resize-none h-60</value>
      <webElementGuid>b0723dc7-e6b3-457c-acda-58d165824346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tsldescription&quot;)</value>
      <webElementGuid>200e0976-b539-4610-9139-8a9c15b26c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='tsldescription']</value>
      <webElementGuid>f9ff0025-ffb3-4504-966b-3afd9a499a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div[2]/div/div/div[3]/textarea</value>
      <webElementGuid>48f8f5e5-5a0b-46b7-9e76-6c06aec69429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>078fef50-d82f-4d6d-919d-385de8006e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'tsldescription' and @type = 'textarea' and @name = 'description' and @placeholder = 'Tulis Deskripsi']</value>
      <webElementGuid>0e784d0d-310f-4967-8f4d-0ad19d301169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
