<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAddAnswer</name>
   <tag></tag>
   <elementGuidId>314332fd-7ea9-4352-a9ee-67245e6eb131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnaddanswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnaddanswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>431e6447-c0eb-4056-baa4-09b27e3fa030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0b135b7-ed8f-4c1c-882b-774ec65e5e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnaddanswer</value>
      <webElementGuid>80beea40-fc2a-4894-aa3c-cb19a852c009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-white rounded border border-darkblue text-darkblue focus:outline-none px-10 py-2</value>
      <webElementGuid>1cc1fa78-8ffd-4f40-8c27-e9e714be050f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah List Jawaban</value>
      <webElementGuid>bca3c2b5-558e-4ea6-8212-3e7c9f855a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnaddanswer&quot;)</value>
      <webElementGuid>4cb7ffe5-f25f-47aa-82ca-826d202452b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnaddanswer']</value>
      <webElementGuid>fde7feaf-ede1-429a-8efb-c28a8be9f7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>e8742bc3-9e51-4105-86af-97a345de6167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link URL'])[2]/following::button[1]</value>
      <webElementGuid>7bb2ae86-0f1f-4cbd-bbd8-3a83c66b5bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link URL'])[1]/following::button[1]</value>
      <webElementGuid>4911fc02-2df6-48c4-b475-3133264637fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::button[1]</value>
      <webElementGuid>5bd35a2c-bc01-43bd-b509-a6a31da84e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>29b33235-2ba3-451a-b9cd-a2c6a817e493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnaddanswer' and (text() = 'Tambah List Jawaban' or . = 'Tambah List Jawaban')]</value>
      <webElementGuid>00a281a4-fcf3-45bf-ace7-cf2172072394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
