<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDeleteLinkedAnswer</name>
   <tag></tag>
   <elementGuidId>242ad677-2031-4c5b-8497-d96f7f01702e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='{var}'])[1]/following::*[name()='svg'][list icon]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a122bf60-4db2-4dfa-91d3-bd4391bb46e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>308c573d-77fb-470f-8ded-e5d388b7a9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>158cda88-8c3b-4ef1-975b-2849fcc60537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fas</value>
      <webElementGuid>bbe6f156-1511-4a23-a75c-801279158671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>xmark</value>
      <webElementGuid>ef757f60-417d-4a0b-a933-a76991c17e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-xmark border-2 border-secondary-text rounded-full w-2.5 h-2.5 p-0.5 cursor-pointer transition-opacity duration-200 hover:opacity-70 select-none</value>
      <webElementGuid>868947cc-0f4b-446b-8848-fbfa49cb0564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9ef80c9-cb1e-4706-ae24-f4edf7b76721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>a13a3229-99eb-4ecc-a8b6-f876499e997e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 384 512</value>
      <webElementGuid>9e71c09e-0411-4c60-b59d-a746683e4fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;pb-8&quot;]/div[2]/div[@class=&quot;flex justify-between items-start gap-2 h-full&quot;]/form[@class=&quot;chatbot-flow-form w-2/4 flex flex-col h-full p-6 bg-white shadow-md rounded-md border border-gray-300 overflow-auto&quot;]/div[@class=&quot;flex gap-6 mb-10&quot;]/div[@class=&quot;card-form w-full shadow-md rounded-lg border border-gray-300&quot;]/div[@class=&quot;card-body flex flex-col p-6&quot;]/div[@class=&quot;selected-answers h-full max-h-full overflow-auto&quot;]/div[@class=&quot;related-answer flex justify-between items-center text-secondary-text bg-white p-3 border border-secondary-text-3 rounded-md mb-2&quot;]/div[@class=&quot;btndeletelistuseranswer&quot;]/svg[@class=&quot;svg-inline--fa fa-xmark border-2 border-secondary-text rounded-full w-2.5 h-2.5 p-0.5 cursor-pointer transition-opacity duration-200 hover:opacity-70 select-none&quot;]</value>
      <webElementGuid>d4eb1d9f-dddd-406a-857c-f24ee8b5cdc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iya'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>5940dbbf-d05d-4e49-ae0e-39ccf8489202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Jawaban'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>fa22b1dc-5d28-4d47-8a8b-417ed2b4006c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya sudah buat tiket'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>f0c330df-2da7-40b1-a759-27b96244eeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Otomatis'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>0782dedf-94e5-402e-90da-8253d741df9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
