<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDeleteAnswerPesanBuatTiket</name>
   <tag></tag>
   <elementGuidId>4089cfb1-c752-40c8-8ac3-c2600861e107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Link URL'])[list jawaban]/following::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>fa224b21-7fd6-4fd5-9a3a-9137e35da462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1693453277334</value>
      <webElementGuid>58ffa9cc-c5b0-4239-914f-b730dc5aaa76</webElementGuid>
   </webElementProperties>
</WebElementEntity>
