<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPesanSolusi</name>
   <tag></tag>
   <elementGuidId>97eb4f42-78f8-4f1a-93c9-0a3fa8f76044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnsolutionmessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnsolutionmessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>171e9147-5998-4408-bf29-9524f70d93fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsolutionmessage</value>
      <webElementGuid>9fd6f316-d5ae-47e4-a0cd-6466051aa649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block bg-white p-4 border-l-8 border-olddarkblue rounded-md mb-3 shadow-md transition duration-200 select-none text-secondary-text hover:bg-lightbluegrey</value>
      <webElementGuid>f853234c-a783-45c0-b10c-4bb14bdb5f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/flow-chatbot?template=pesan-solusi</value>
      <webElementGuid>25514109-5b50-439d-bdde-ccaa863c10e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesan Solusi</value>
      <webElementGuid>69c16237-74c1-40f0-8b67-719ace8b7c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsolutionmessage&quot;)</value>
      <webElementGuid>24f3f399-5464-4fee-a266-86eed3178274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnsolutionmessage']</value>
      <webElementGuid>1a96c9bd-9af1-49f6-81cf-2cbe834b3987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageTemplate']/div/div/div[2]/div/a[2]</value>
      <webElementGuid>4c27c5e1-5a25-4dc8-a3a9-3bf568232fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pesan Solusi')]</value>
      <webElementGuid>18867610-8418-46c6-acde-abecab93fc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Pembuka'])[1]/following::a[1]</value>
      <webElementGuid>9b0b3b17-67ec-4dc1-b38f-24f3a91d545f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Pesan'])[1]/following::a[2]</value>
      <webElementGuid>fa63fef0-a4cc-40d7-b0f3-c24b6a550141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Penutup'])[1]/preceding::a[1]</value>
      <webElementGuid>a1c39a6e-4336-4c03-b7f4-2c36279b678e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Eror'])[1]/preceding::a[2]</value>
      <webElementGuid>7f9b0483-7114-4936-9717-3ff7bcacc6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesan Solusi']/parent::*</value>
      <webElementGuid>d8c875d9-85b7-468c-bab7-12c9dafce910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings/flow-chatbot?template=pesan-solusi')]</value>
      <webElementGuid>82679882-5f45-4e13-9d0d-21fbc0eef485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/a[2]</value>
      <webElementGuid>1424ead4-0035-44aa-9920-04bfb65b6d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnsolutionmessage' and @href = '/settings/flow-chatbot?template=pesan-solusi' and (text() = 'Pesan Solusi' or . = 'Pesan Solusi')]</value>
      <webElementGuid>370ccd06-1e6d-418c-b741-abbbf23d71c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
