<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPesanBuatTiket</name>
   <tag></tag>
   <elementGuidId>7c796598-9580-4cec-aaa8-cf6f3b083473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btncreateticketmessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btncreateticketmessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a84639d-d801-48e5-a5f6-677d5bfe4944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btncreateticketmessage</value>
      <webElementGuid>49074a72-614d-4d0a-b5b0-2ea93f271f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block bg-white p-4 border-l-8 border-olddarkblue rounded-md mb-3 shadow-md transition duration-200 select-none text-secondary-text hover:bg-lightbluegrey</value>
      <webElementGuid>8703b37d-156b-4ee7-8f15-78ffaecc0bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/flow-chatbot?template=pesan-tiket</value>
      <webElementGuid>cbb5daf3-a395-46fc-9bb9-3fc256c6993e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesan Buat Tiket</value>
      <webElementGuid>6e08a543-a198-4cef-8433-c6e41d62c734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btncreateticketmessage&quot;)</value>
      <webElementGuid>0c0bc72b-7095-4d4c-a61f-435084fdb977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btncreateticketmessage']</value>
      <webElementGuid>286ca3c6-cd7b-4a74-b52f-cade6f54e285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageTemplate']/div/div/div[2]/div/a[5]</value>
      <webElementGuid>bedeaa73-b134-4daf-9644-f492eec63270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pesan Buat Tiket')]</value>
      <webElementGuid>fff1861c-8468-4a20-8403-b64d7823ae32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Eror'])[1]/following::a[1]</value>
      <webElementGuid>4c998825-972f-455d-b51c-3a7710e78bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Penutup'])[1]/following::a[2]</value>
      <webElementGuid>e1b07aa6-0938-4b08-8242-94f55eb09763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Timeout'])[1]/preceding::a[1]</value>
      <webElementGuid>029e5dfc-9992-46b2-abd3-446ac42ffb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanya &amp; Jawab'])[1]/preceding::a[2]</value>
      <webElementGuid>8975e6ac-0c32-4a80-afba-74825c3f23e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesan Buat Tiket']/parent::*</value>
      <webElementGuid>6c4f4fd8-9c53-4ab1-bb79-c579694fa7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings/flow-chatbot?template=pesan-tiket')]</value>
      <webElementGuid>8dcf568e-9fd7-4103-87e1-7fa3a5799a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/a[5]</value>
      <webElementGuid>bf76efe8-2a96-443a-b4aa-e0d71a21a435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btncreateticketmessage' and @href = '/settings/flow-chatbot?template=pesan-tiket' and (text() = 'Pesan Buat Tiket' or . = 'Pesan Buat Tiket')]</value>
      <webElementGuid>d3e2c31b-30af-484c-84aa-4bb8bb047cbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
