<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPesanPenutup</name>
   <tag></tag>
   <elementGuidId>4d2c93ab-0b56-466b-9e96-cb752a2b7756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnclosingmessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnclosingmessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>861dfd8e-3941-4fa9-b220-bf5ffc25df0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnclosingmessage</value>
      <webElementGuid>64e970c5-0daa-4358-96df-6d44867918b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block bg-white p-4 border-l-8 border-olddarkblue rounded-md mb-3 shadow-md transition duration-200 select-none text-secondary-text hover:bg-lightbluegrey</value>
      <webElementGuid>afd865c0-13c5-48ec-8397-4bc1c1e71919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/flow-chatbot?template=pesan-penutup</value>
      <webElementGuid>5be7a1c7-3a1f-4f01-91fc-db18119afab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesan Penutup</value>
      <webElementGuid>72fc78df-5ddf-4a55-956e-fbe36b24404e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnclosingmessage&quot;)</value>
      <webElementGuid>ff42f0fa-ab68-4b25-88a8-cd7bc558a8bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnclosingmessage']</value>
      <webElementGuid>00035f2b-7316-463d-8279-cc3115fa9405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageTemplate']/div/div/div[2]/div/a[3]</value>
      <webElementGuid>1bd0c443-de88-4fec-aac0-8a926d4f0cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pesan Penutup')]</value>
      <webElementGuid>ca9800c0-0c5f-440a-ae26-184ec7d3b4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Solusi'])[1]/following::a[1]</value>
      <webElementGuid>94b092b0-9f02-4daa-9c14-62d0d1a188ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Pembuka'])[1]/following::a[2]</value>
      <webElementGuid>22bcf60a-9be6-4748-abef-fc6f12343027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Eror'])[1]/preceding::a[1]</value>
      <webElementGuid>bc0cbf05-f37a-4458-8e5b-33d3b7eed7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Buat Tiket'])[1]/preceding::a[2]</value>
      <webElementGuid>c623f67f-aaf8-4432-9284-d85e26a17e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesan Penutup']/parent::*</value>
      <webElementGuid>435e5e44-19b5-47de-8e6d-86ac1c4cd300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings/flow-chatbot?template=pesan-penutup')]</value>
      <webElementGuid>299cc266-6bb2-4bb0-90f9-0ed1db5e3065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/a[3]</value>
      <webElementGuid>724235a3-d8c9-48e3-9d2b-ba734f2c8a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnclosingmessage' and @href = '/settings/flow-chatbot?template=pesan-penutup' and (text() = 'Pesan Penutup' or . = 'Pesan Penutup')]</value>
      <webElementGuid>8dfc3719-39c6-42bd-8df3-db32d841f57c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
