<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPesanEror</name>
   <tag></tag>
   <elementGuidId>18bb9ce2-c4bc-4463-bd7c-2dcdafc919a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnerrormessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnerrormessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65075620-1e42-414d-9dd4-0f272b6650e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnerrormessage</value>
      <webElementGuid>186162fe-88e0-4905-ac37-11db0af17de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block bg-white p-4 border-l-8 border-olddarkblue rounded-md mb-3 shadow-md transition duration-200 select-none text-secondary-text hover:bg-lightbluegrey</value>
      <webElementGuid>dc913f8f-6fec-4318-94dd-8308b2e3ff30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/flow-chatbot?template=pesan-eror</value>
      <webElementGuid>e022b4bf-47e9-4726-88cd-1542df794d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesan Eror</value>
      <webElementGuid>df654a20-9e8a-4ec9-b007-7b5aa6d15cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnerrormessage&quot;)</value>
      <webElementGuid>c47f85ab-582c-4d10-83bb-b3921ac13ff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnerrormessage']</value>
      <webElementGuid>c3f5ed9b-17b3-491a-b57f-048e9b0ec237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageTemplate']/div/div/div[2]/div/a[4]</value>
      <webElementGuid>741c99bf-1888-4574-b659-961c508d54e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pesan Eror')]</value>
      <webElementGuid>9b9568f9-5aed-4723-bc58-ae80b34122f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Penutup'])[1]/following::a[1]</value>
      <webElementGuid>d99eeab4-8469-4962-a12c-5ade5939e01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Solusi'])[1]/following::a[2]</value>
      <webElementGuid>e28b4f7d-48d9-4240-9cc6-bde4d542dfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Buat Tiket'])[1]/preceding::a[1]</value>
      <webElementGuid>f309ed0f-647b-48f4-96ba-65253fe658a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Timeout'])[1]/preceding::a[2]</value>
      <webElementGuid>b495ac72-7ec6-4ed6-af7d-4ed0e0df65da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesan Eror']/parent::*</value>
      <webElementGuid>e2edf94b-41c2-4bcf-b57e-f34c1312a36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings/flow-chatbot?template=pesan-eror')]</value>
      <webElementGuid>d43a36fd-2b05-46b0-85df-d3a0b0e7ceff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/a[4]</value>
      <webElementGuid>99243e44-a733-4849-aade-7304616b8550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnerrormessage' and @href = '/settings/flow-chatbot?template=pesan-eror' and (text() = 'Pesan Eror' or . = 'Pesan Eror')]</value>
      <webElementGuid>16bb3887-dd39-44ec-9f61-493d63409c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
