<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPesanPembuka</name>
   <tag></tag>
   <elementGuidId>3ce0d720-f46d-4d22-bd47-c756a273668e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btngreetingmessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btngreetingmessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2230db63-b953-424a-a6ce-6223e7b4574a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btngreetingmessage</value>
      <webElementGuid>789cd646-55ac-4ed1-b061-4dbe40f09729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block bg-white p-4 border-l-8 border-olddarkblue rounded-md mb-3 shadow-md transition duration-200 select-none font-bold text-white bg-white-3</value>
      <webElementGuid>0e359624-dc77-4860-b3bd-e4624c7fb2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/flow-chatbot?template=pesan-pembuka</value>
      <webElementGuid>6232e63c-cf43-4396-93f3-0b3d4a54e2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesan Pembuka</value>
      <webElementGuid>417075a9-50cd-41da-80c3-1eecf4045100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btngreetingmessage&quot;)</value>
      <webElementGuid>3ae912ca-8a62-42d2-8039-68b95689d876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btngreetingmessage']</value>
      <webElementGuid>8a21eaf8-2a2c-4df4-b234-849843c53ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageTemplate']/div/div/div[2]/div/a</value>
      <webElementGuid>510640f8-103e-4fb5-8d6f-38efa792e4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pesan Pembuka')]</value>
      <webElementGuid>c4c7cd94-56e0-493c-9e97-4026c061b771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Pesan'])[1]/following::a[1]</value>
      <webElementGuid>cd899cf6-cb6b-4895-97c2-e5b15feb0a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Template Pesan Otomatis'])[1]/following::a[1]</value>
      <webElementGuid>a519d5c4-ad93-4b02-b333-6e5bb5106dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Solusi'])[1]/preceding::a[1]</value>
      <webElementGuid>87af86cb-22b6-4d8b-b686-ea38b37b01dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Penutup'])[1]/preceding::a[2]</value>
      <webElementGuid>320b6ece-fcfb-4fbc-b95a-105d1b325206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesan Pembuka']/parent::*</value>
      <webElementGuid>ca51ae25-9934-4758-b979-f1a100e88b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings/flow-chatbot?template=pesan-pembuka')]</value>
      <webElementGuid>006219e0-c25c-4ba4-bffb-dfbfbd3adeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>a0aae705-4869-4513-b14b-7ffa888d3dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btngreetingmessage' and @href = '/settings/flow-chatbot?template=pesan-pembuka' and (text() = 'Pesan Pembuka' or . = 'Pesan Pembuka')]</value>
      <webElementGuid>0eb0ba1c-28c1-4a9e-b93b-117cb8dac5aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
