<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPesanTimeout</name>
   <tag></tag>
   <elementGuidId>f41b3ef7-446d-4e46-a22b-390bfc70c6d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btntimeoutmessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btntimeoutmessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bbce7071-14f5-4cd2-b6c8-9e3eb3ab37d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btntimeoutmessage</value>
      <webElementGuid>7aae2bc1-499f-42f1-9b4b-ce2f42c088af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block bg-white p-4 border-l-8 border-olddarkblue rounded-md mb-3 shadow-md transition duration-200 select-none text-secondary-text hover:bg-lightbluegrey</value>
      <webElementGuid>53c318a2-eef1-45ea-9060-633ad7aaa2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/flow-chatbot?template=pesan-timeout</value>
      <webElementGuid>0ead28c4-3efd-40eb-bf16-2baf06ee93d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesan Timeout</value>
      <webElementGuid>b2bf4422-84ba-4deb-8db0-f8974d008d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btntimeoutmessage&quot;)</value>
      <webElementGuid>adfee31e-60c8-4616-becc-e617973a9704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btntimeoutmessage']</value>
      <webElementGuid>660f5add-d893-42c8-b0ea-4ab1e5eefa3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageTemplate']/div/div/div[2]/div/a[6]</value>
      <webElementGuid>e77a3d49-8047-4510-a192-4a309d7c8ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pesan Timeout')]</value>
      <webElementGuid>6a3ec3cd-51c7-4168-bf19-f9d51621529e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Buat Tiket'])[1]/following::a[1]</value>
      <webElementGuid>7660e2c0-e1ee-4aad-9b43-2ef850e577e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Eror'])[1]/following::a[2]</value>
      <webElementGuid>f811d16b-1e37-4e38-9319-deac3c21eb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanya &amp; Jawab'])[1]/preceding::a[1]</value>
      <webElementGuid>a1022207-609b-4f5e-8aed-2f33815d50ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk apa yang akan anda pilih hari ini'])[1]/preceding::a[1]</value>
      <webElementGuid>b7a068ee-3730-4f3e-9cd9-68cceb0b452d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesan Timeout']/parent::*</value>
      <webElementGuid>b25e9cea-6a63-4b2b-8969-724754702dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings/flow-chatbot?template=pesan-timeout')]</value>
      <webElementGuid>e5f88149-d271-4b08-b66e-a88ce224cdf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/a[6]</value>
      <webElementGuid>655407c9-4620-4816-9e3c-d448617355fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btntimeoutmessage' and @href = '/settings/flow-chatbot?template=pesan-timeout' and (text() = 'Pesan Timeout' or . = 'Pesan Timeout')]</value>
      <webElementGuid>45577cca-11db-485f-80a5-904d580a88fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
