<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTinggalkanHalaman</name>
   <tag></tag>
   <elementGuidId>e02b06c6-9f7d-4d18-9163-4493fd8b3dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>def965bc-aa99-49aa-9554-1dbc716d0dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5035f55d-7ffa-421c-8e44-b6369c4f420c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnno</value>
      <webElementGuid>5a72af39-0c1a-47f7-a479-2560badf4874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>false bg-transparent rounded-md border border-nexcaredefault text-nexcaredefault focus:outline-none font-medium px-6 py-2</value>
      <webElementGuid>083d18a6-9a1a-4fc7-b7a7-55e7cfb703db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tinggalkan Halaman</value>
      <webElementGuid>1f798223-4ee7-4e5f-804b-79e302cd6bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnno&quot;)</value>
      <webElementGuid>02cde844-5b9a-4982-8508-3c1d60d526ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnno']</value>
      <webElementGuid>39aad499-4015-4db3-b490-a0103703cfef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/div[2]/div/div/div[3]/button</value>
      <webElementGuid>89bb2507-2025-4ce0-9bb3-f989133be4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perubahan yang Anda buat mungkin tidak disimpan'])[1]/following::button[1]</value>
      <webElementGuid>3ad52fab-4393-4b71-bd6c-f67ebb99db0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinggalkan Halaman'])[1]/following::button[1]</value>
      <webElementGuid>3fca1c75-b16f-4a82-9919-1e6a3cd0fd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tetap Dihalaman'])[1]/preceding::button[1]</value>
      <webElementGuid>7fe80878-d556-462f-9002-2594f0d92abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::button[2]</value>
      <webElementGuid>63aa503b-8006-4781-8f91-44ddaa4d03e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>a025d1f1-b800-46bb-a8e1-2b3652ee9781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnno' and (text() = 'Tinggalkan Halaman' or . = 'Tinggalkan Halaman')]</value>
      <webElementGuid>41ba8feb-3b8e-487c-842d-8bbace78a4df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
