<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Answer</name>
   <tag></tag>
   <elementGuidId>92451a4a-861b-463f-8e3a-8d80eb186540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div[3]/div[2]/div[2]/div/form/div[1]/div/div[2]/div/div[2]/div/div[${indeks}]/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.tslanswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe520b85-5d8e-43bd-aad2-2c72f2ba9cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tslanswer</value>
      <webElementGuid>a7359e37-d923-4a4e-8998-78683d6575d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61f25ca0-a5c1-4d35-af87-4074a2aaeb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Jawaban</value>
      <webElementGuid>fdf4f8b4-524c-4432-9784-58d2adf58e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7c527b0b-514b-4aeb-9c4a-0e6f03becb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Iya</value>
      <webElementGuid>fb5f3716-cc83-442b-9103-5965eaaa7d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;pb-8&quot;]/div[2]/div[@class=&quot;flex justify-between items-start gap-2 h-full&quot;]/form[@class=&quot;chatbot-flow-form flex flex-col w-2/4 h-full p-6 bg-white shadow-md rounded-md border border-gray-300 overflow-auto&quot;]/div[@class=&quot;mb-10&quot;]/div[@class=&quot;card-form w-full shadow-md rounded-lg&quot;]/div[@class=&quot;card-body bg-white p-6 rounded-b-lg border border-gray-300&quot;]/div[@class=&quot;flex h-full gap-10&quot;]/div[@class=&quot;flex-1 flex flex-col h-full&quot;]/div[@class=&quot;max-h-full mb-3 overflow-auto relative&quot;]/div[@class=&quot;LinkedInput_linked-input__2wnJF answer-option mb-3&quot;]/div[@class=&quot;LinkedInput_input__1zSB6&quot;]/input[@class=&quot;tslanswer&quot;]</value>
      <webElementGuid>7999ea5b-8e99-4bdf-ada1-7e2d8dfaab40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Iya']</value>
      <webElementGuid>f400a325-9549-4c40-a462-76b922727962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div/div/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>0001d950-db7b-47b3-87f2-54a6afe11489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>9db8beaa-0b24-41c0-a3a3-99fa14200f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Tulis Jawaban']</value>
      <webElementGuid>6c39b2b4-9452-4f19-9b70-de9760aab791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
