<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TimeoutParameter</name>
   <tag></tag>
   <elementGuidId>ace95d80-69fb-427c-8f93-b0a1f77511fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tsltimeoutmessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tsltimeoutmessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cb44135-f5ba-4059-8767-b671b3bb1028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tsltimeoutmessage</value>
      <webElementGuid>b048d5d4-57f0-4e22-afe4-e0978c2a3cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-3 py-3</value>
      <webElementGuid>4d497fdc-7929-4247-b908-799713e858fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23f93f3c-797c-4079-8505-c59ff80bf88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis batas waktu pesan</value>
      <webElementGuid>9ef0093b-4202-4b88-909d-e06e3c6b9164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chatTimeout</value>
      <webElementGuid>733f3b8c-5377-4423-9268-3d3ee4a7f4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>ee93ee1f-7d8d-4558-b4f4-e1c94cd3b7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tsltimeoutmessage&quot;)</value>
      <webElementGuid>8140d771-8080-41f1-b1b2-bf0905e9575a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tsltimeoutmessage']</value>
      <webElementGuid>1a0ee191-311d-4e45-b817-8ba362a62684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>b8da132f-a7b5-4283-be65-9c8597a36720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e733a276-2fe3-49f7-a925-2d4446578596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tsltimeoutmessage' and @type = 'text' and @placeholder = 'Tulis batas waktu pesan' and @name = 'chatTimeout']</value>
      <webElementGuid>8adc01fe-cb26-4199-8cc0-45caf43491a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
