<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ClosingParameter</name>
   <tag></tag>
   <elementGuidId>1f6c1901-c554-4f7e-8dee-fdc0fb7c3fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tslclosingmessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tslclosingmessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bedffe4b-5584-4adb-af7e-a33f6dd1b7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslclosingmessage</value>
      <webElementGuid>24f1cccb-4db9-415f-bacd-33f78dc57d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-3 py-3</value>
      <webElementGuid>567cb81a-eb5f-4961-ae68-2eb86bba0e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b0f7349-35d5-42c7-867e-9efb718937c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis durasi penutupan</value>
      <webElementGuid>790a14b2-dd61-4ec8-bc94-d9f9660e0cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>closingDuration</value>
      <webElementGuid>234bf778-ef6b-4826-b653-99727ed9ed2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>999812d4-1bc8-43b4-90f8-92df127ca3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tslclosingmessage&quot;)</value>
      <webElementGuid>8ca38d2e-cb51-44fb-95bf-54b812b9a3a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tslclosingmessage']</value>
      <webElementGuid>3a2c9b1e-cc14-4542-9aa8-0bad5b11908b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div/div/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>aa0b628e-24d6-45d5-86ad-4bb65e15b7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>2ed77994-140d-4b89-bb11-9a7cb08c03bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tslclosingmessage' and @type = 'text' and @placeholder = 'Tulis durasi penutupan' and @name = 'closingDuration']</value>
      <webElementGuid>85234ec7-6761-4160-9377-9d550e622402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
