<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lupa kata sandi</name>
   <tag></tag>
   <elementGuidId>47f0d13b-75ca-4a17-b258-3d2076eb901e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-gray-500</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/reset-password' and (text() = 'Lupa kata sandi?' or . = 'Lupa kata sandi?')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/form/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>42e6a3fb-41e8-4bed-9cf5-18945bd3747a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-500</value>
      <webElementGuid>c1846cdb-e456-41e7-8a0f-c19fc94d7981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/reset-password</value>
      <webElementGuid>f19bdbb0-50b3-41e9-8e4d-0c3ac18a9710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lupa kata sandi?</value>
      <webElementGuid>5f1be122-f4d4-4b43-8ba7-5556f6ba200c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;w-screen h-screen bg-white relative&quot;]/form[@class=&quot;absolute top-40 right-56 text-gray-600&quot;]/div[@class=&quot;font-medium text-center py-5&quot;]/a[@class=&quot;text-gray-500&quot;]</value>
      <webElementGuid>ddeab15e-9617-4ca4-9c8a-b6f74fa4e80f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div[4]/a</value>
      <webElementGuid>37dde638-6a05-44f2-ba4a-502c5cd42dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lupa kata sandi?')]</value>
      <webElementGuid>1be5f84a-05d0-49bb-b7b0-547b25bcd639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::a[1]</value>
      <webElementGuid>d29cf1a2-f364-4d0a-bfc5-ed480ea9e73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[1]</value>
      <webElementGuid>09428972-1e8c-40d3-b288-99faec38eff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::a[1]</value>
      <webElementGuid>673d5195-b2b7-45a5-b823-4a26cbb0b344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lupa kata sandi?']/parent::*</value>
      <webElementGuid>c42ab71f-ea6b-463b-9d5b-6f0ada6812e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/reset-password')]</value>
      <webElementGuid>737e0c58-93e1-45ef-aa32-60de390912c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>065826ab-720f-4af8-8215-484e68c4fc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/reset-password' and (text() = 'Lupa kata sandi?' or . = 'Lupa kata sandi?')]</value>
      <webElementGuid>f9da44f1-3d88-4f5a-9b15-700a48dd9412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
