<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Version2.1.0_Path_6398</name>
   <tag></tag>
   <elementGuidId>c265ef37-1e19-46fc-a812-f7f7a94cdf8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//path[@id = 'Path_6398']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Path_6398</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>075fe89f-b793-42a9-afb3-65c801b961ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Path_6398</value>
      <webElementGuid>666ca576-b5ed-4b14-b7b7-7f15e2f9ffad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Path 6398</value>
      <webElementGuid>0241a1e5-bde2-498b-9239-90b031a3bbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M1.5,1.5l20,20</value>
      <webElementGuid>9ee07f14-ddf2-4eac-b27a-beea933b0051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9df498fd-5bef-42fa-9321-92cf8f49ce04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#4e5b65</value>
      <webElementGuid>6114d8a0-1915-48c1-a068-fc61453518c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>b41a2183-4de3-488c-8339-3041029b44a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>f1d5421e-edb6-4486-9bc2-b5a4c79cda2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d52462e8-e6f3-4a7e-b60e-563bd1aec561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Path_6398&quot;)</value>
      <webElementGuid>c94c38d9-6f53-4b5c-9642-da5cf302e10a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//path[@id = 'Path_6398']</value>
      <webElementGuid>29619100-6a43-4b95-85b0-339c07cb8019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
