<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnLogOut</name>
   <tag></tag>
   <elementGuidId>6ea9e72b-0024-4383-8867-ced67bd0970f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btnlogout.cursor-pointer.ml-5 > svg</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;topbar shadow-md flex justify-between items-center px-10&quot;]/div[@class=&quot;date-time-notification flex items-center&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;btnlogout cursor-pointer ml-5&quot;]/svg[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='btnlogout cursor-pointer ml-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>9d39444f-6972-4452-8e6d-65eafbbd746c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>bfb32cef-5bc0-4968-9ee5-649b8a9a5ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>e6a75d39-17e7-43f9-8498-5103f3e74462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>657c47e3-482d-4934-be1a-3cb004ce2c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2e67b819-ea71-462a-a2ea-e0a2fcfb2793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 25 25</value>
      <webElementGuid>c3c7e3f1-02dc-4849-b551-b8092db6b1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;topbar shadow-md flex justify-between items-center px-10&quot;]/div[@class=&quot;date-time-notification flex items-center&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;btnlogout cursor-pointer ml-5&quot;]/svg[1]</value>
      <webElementGuid>6bc6d89a-210c-4564-9293-f349bc82e488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>a9bf0b1c-d344-4fa7-8c97-84b508354f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin NexCare'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>c158497d-bef9-40b9-8cef-d7671894d93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Principal'])[1]/preceding::*[name()='svg'][9]</value>
      <webElementGuid>276eaa06-1e9c-46ce-9024-e095150fbbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[1]/preceding::*[name()='svg'][10]</value>
      <webElementGuid>66d0860d-749f-4a27-ad53-59bfb6185e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
