<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tinggalkan Halaman</name>
   <tag></tag>
   <elementGuidId>91d55a62-e6b9-4b6f-81e6-344036a9037e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnno']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnno</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fdfc589c-a4d8-4595-a81c-e30642f73dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82af25a7-e78a-4552-a012-edd28045d83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnno</value>
      <webElementGuid>39f57557-e917-4a8f-9210-d0a1dbaa4cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>false bg-transparent rounded-md border border-nexcaredefault text-nexcaredefault focus:outline-none font-medium px-6 py-2</value>
      <webElementGuid>c1e1c34f-8348-42d3-aecc-84694a4a8e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tinggalkan Halaman</value>
      <webElementGuid>becd3106-3c1b-441b-a9ef-a0355db6ec60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnno&quot;)</value>
      <webElementGuid>cf54b11b-bced-4039-9eb8-25a675e0c849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnno']</value>
      <webElementGuid>82c5511a-d94e-43dd-81e1-2b911834a3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/div[2]/div/div/div[3]/button</value>
      <webElementGuid>9d9e6355-d991-406a-80c8-3f3561847a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perubahan yang Anda buat mungkin tidak disimpan'])[1]/following::button[1]</value>
      <webElementGuid>fda12157-978c-4328-8ccf-7be081240555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tinggalkan Halaman'])[1]/following::button[1]</value>
      <webElementGuid>dc9df999-7123-4dce-96ac-663e8ec4010b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tetap Dihalaman'])[1]/preceding::button[1]</value>
      <webElementGuid>2718c9d2-1526-48cb-a1d3-2bb7e95b58b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::button[2]</value>
      <webElementGuid>ce188f6a-f018-4abc-a136-d862d4d3f63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>5daa0aef-4ae6-4bed-9bd5-e96effe72e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnno' and (text() = 'Tinggalkan Halaman' or . = 'Tinggalkan Halaman')]</value>
      <webElementGuid>161d2b64-bd7e-4a7c-80e6-87fa56defb38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
