<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>ef861d4f-e80b-4012-ab3e-765e0bb24e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnsave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnsave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0aa3ec0-6c8e-4b5a-9ffd-cdb05be45396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsave</value>
      <webElementGuid>5ffa12e7-58b9-4635-9f64-4ae6a6345af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined bg-nexcaredefault rounded border border-darkblue text-white focus:outline-none px-10 py-2</value>
      <webElementGuid>1d887aac-a51a-4716-b73b-218cdb8f6982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>b47b804e-588a-45e4-8eed-ceef511bb643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsave&quot;)</value>
      <webElementGuid>89d1877b-4ea2-4cf4-a527-25bb25566805</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnsave']</value>
      <webElementGuid>c9730e11-1bfc-44f1-87e5-6be8906cca01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div[2]/button[2]</value>
      <webElementGuid>166e17d8-02d0-48ce-bde0-32c5d7102962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>488aded6-a4f1-4f5b-b56c-20430cc1a5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hai ini Ola, ada yg bisa dibantu?'])[1]/following::button[2]</value>
      <webElementGuid>1e5c48a5-0970-4c28-ae2d-6657946469de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OLA'])[1]/preceding::button[1]</value>
      <webElementGuid>102677dc-035e-4d4e-a551-8921be1e02f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Otomatis'])[3]/preceding::button[1]</value>
      <webElementGuid>93949451-9f23-4891-b38c-7fc7ef4c3850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>c0df01e7-64c5-4594-93b3-ba07f045c6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>c322b35b-79a2-44e8-be18-ce025ee5478f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnsave' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>2058675c-2ec2-4655-973d-6ac272da45c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
