<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyPIC_Name</name>
   <tag></tag>
   <elementGuidId>302e69cd-8d0d-4cf0-b04f-92fff6e49fda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[.='${pic_name}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
