<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkbx_OnlineOnly</name>
   <tag></tag>
   <elementGuidId>4c034b09-d91b-42ed-a430-2fa2dfb36e59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onlyOnlineCustomerService</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='onlyOnlineCustomerService']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4ae8d98-23bd-491a-8718-86211637c33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8ea34fc2-916f-4054-9f4d-5aaa94c37c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5</value>
      <webElementGuid>05db5562-1a27-49d3-8a6e-43513e502074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onlyOnlineCustomerService</value>
      <webElementGuid>50d9238d-c7f6-4c5d-a8f1-8536008f4286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7adc692c-7234-4e2e-870e-d13df6199137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onlyOnlineCustomerService&quot;)</value>
      <webElementGuid>0973c184-6a6d-4563-bdf5-8a3d83e04c5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='onlyOnlineCustomerService']</value>
      <webElementGuid>95118f68-4487-409f-8899-eaa8d2f9ec80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>482448bf-6652-4e56-835b-0bd0899b5d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>78a81556-9676-44bd-8e97-5c94a042601b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'onlyOnlineCustomerService']</value>
      <webElementGuid>136e48cd-0b25-4213-899b-84d780cdf3fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
