<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddCategory</name>
   <tag></tag>
   <elementGuidId>2034535c-6172-42de-9680-e75b5db10a54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnaddcategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnaddcategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e69478fd-c7e7-47d3-8401-9293570b3691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center cursor-pointer bg-olddarkblue text-white py-2 px-6 rounded-lg</value>
      <webElementGuid>4d43956f-08e9-4d4d-a062-274c4b09a681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnaddcategory</value>
      <webElementGuid>60de60b8-9b7c-4e13-aadf-2fe9c9bc1b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/kms/category/add</value>
      <webElementGuid>d63a2dcd-5640-4737-bcb7-675dc95403c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Kategori</value>
      <webElementGuid>c00c861e-b591-49a5-a2a0-a5a0e698cd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnaddcategory&quot;)</value>
      <webElementGuid>66990c9d-f1bc-433e-88bc-446d9ebd12f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnaddcategory']</value>
      <webElementGuid>02c1e3ef-f6d6-431e-81ab-fdfdc2ba75f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/a</value>
      <webElementGuid>f59377c4-b998-4864-9357-dd35d114bd7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Knowledge Management Sistem'])[1]/following::a[1]</value>
      <webElementGuid>254b1585-494f-4cf3-b02b-b4787155c36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KMS'])[2]/following::a[1]</value>
      <webElementGuid>2a985b97-2eb6-43e2-a72a-3fa7a84dd3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level 1'])[1]/preceding::a[1]</value>
      <webElementGuid>61bc3b3a-38c1-4ed8-9a02-2573cd7a0dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings/kms/category/add')]</value>
      <webElementGuid>666c0b49-387d-4683-909b-3b5ac1f761b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a</value>
      <webElementGuid>d71f7899-ee39-4517-b81e-b013209c8b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnaddcategory' and @href = '/settings/kms/category/add' and (text() = 'Tambah Kategori' or . = 'Tambah Kategori')]</value>
      <webElementGuid>a1a60a3b-4778-47b3-b033-c2d1174fb342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
