<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ubah</name>
   <tag></tag>
   <elementGuidId>9ddc489c-c297-4a17-a3ea-c344ae68e1eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnedit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnedit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71827902-67e7-46df-8b6c-bf0405156a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnedit</value>
      <webElementGuid>72ad0649-67d2-4a12-85ec-ab64a280fd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-olddarkblue text-white py-2 px-6 rounded-lg font-medium</value>
      <webElementGuid>764e063d-57fa-47d5-bdc8-50eb1f41a49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>c78a715c-818f-4d6e-ba93-34b8df0119d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnedit&quot;)</value>
      <webElementGuid>d22e87b3-0049-4c54-bf78-0e3f942a4b33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnedit']</value>
      <webElementGuid>03d9469e-ea76-4e42-a823-c8599564e2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>2ae08e7e-0015-42a5-ae1c-75b772d78ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>0fabca56-1a7e-4224-9ad5-75fcdb210bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnedit' and (text() = 'Ubah' or . = 'Ubah')]</value>
      <webElementGuid>9934ff71-09bf-49cc-b766-e06638578bf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
