<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_validation</name>
   <tag></tag>
   <elementGuidId>e83e2046-f673-4e72-959f-009d247787c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-lg.whitespace-normal.mb-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div[2]/div[4]/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5f2e637-a8e5-469d-91ea-785194d40c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-lg whitespace-normal mb-3</value>
      <webElementGuid>9ff22482-e45f-4582-adb3-123673247ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jumlah karakter pada category harus lebih besar dari 2</value>
      <webElementGuid>929eb832-186a-4d1b-b716-394b1217efb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;white-container pb-24&quot;]/div[@class=&quot;w-full bg-white border border-gray-300 rounded-lg p-8&quot;]/div[@class=&quot;relative&quot;]/div[4]/div[@class=&quot;transition duration-300 flex justify-center items-center fixed inset-0 outline-none focus:outline-none opacity-1 transform scale-100&quot;]/div[@class=&quot;border-0 rounded-2xl shadow bg-white outline-none focus:outline-none p-10 text-center text-gray-600 alert-box&quot;]/div[@class=&quot;text-lg whitespace-normal mb-3&quot;]</value>
      <webElementGuid>59198f54-cfec-4b42-a66c-8865499c7d49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div[2]/div[4]/div/div/div[3]</value>
      <webElementGuid>69bf3c9f-fefc-4a33-ba67-8b251d3f8532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oops, Gagal'])[1]/following::div[1]</value>
      <webElementGuid>3c889b33-df56-479c-b529-e0f67e65171e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[1]/following::div[8]</value>
      <webElementGuid>966c41b6-732f-4619-8e2e-d8e57cf27b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[2]/preceding::div[1]</value>
      <webElementGuid>891ff863-61ba-4647-b5c0-e850e58cc9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[1]/preceding::div[1]</value>
      <webElementGuid>b288a881-c586-4b85-8e79-fc653a4413f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jumlah karakter pada category harus lebih besar dari 2']/parent::*</value>
      <webElementGuid>94e055d2-325d-4211-9174-859665744778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]</value>
      <webElementGuid>0b2ba840-a63f-4ca6-9c94-1a179332f94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jumlah karakter pada category harus lebih besar dari 2' or . = 'Jumlah karakter pada category harus lebih besar dari 2')]</value>
      <webElementGuid>ee4d7535-21e3-4684-97ec-d0ba89387e39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
