<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkbx_inputKMS</name>
   <tag></tag>
   <elementGuidId>254277cf-e411-4676-ab28-cc10ce062d7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ckbaddkms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ckbaddkms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5330d711-3f33-41e4-a7ce-0b98ba55fdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ckbaddkms</value>
      <webElementGuid>f0b69193-e496-4191-babc-044e9c491db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f3c710f-ecfd-4181-8390-df6b607c2413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ckbaddkms&quot;)</value>
      <webElementGuid>c792664f-b7ff-4f00-aba7-908268bd57dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ckbaddkms']</value>
      <webElementGuid>eb438878-3339-4477-b27c-51c88e4ca7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div[2]/div[4]/div/div/div[2]/div/div/input</value>
      <webElementGuid>7525367b-0078-4f8f-9b98-4d0e435a83be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/input</value>
      <webElementGuid>f379ad68-7fc2-4f20-b3d5-728254faab25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ckbaddkms' and @type = 'checkbox']</value>
      <webElementGuid>12e8bdd5-e13a-4e19-b06c-2eb616f8a4e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
