<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BacktoTop</name>
   <tag></tag>
   <elementGuidId>4b9c5e47-752f-4897-9020-9530caae0ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.text-3xl.font-bold.space-x-4 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7916b593-11e2-4929-977f-3c6114d6eeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Knowledge Management Sistem</value>
      <webElementGuid>6bc85a80-81fe-4b84-9331-124a26b20893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;space-y-3 h-breadcrumb&quot;]/div[@class=&quot;flex items-center text-3xl font-bold space-x-4&quot;]/div[1]</value>
      <webElementGuid>3b130104-d2e1-4678-9c9b-91c94a23e9ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div/div[2]/div</value>
      <webElementGuid>cc197884-3f37-48c4-ac40-f7f6654ed219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div</value>
      <webElementGuid>387453e5-7bcd-4a9e-bb18-d1a64ecf59d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Knowledge Management Sistem' or . = 'Knowledge Management Sistem')]</value>
      <webElementGuid>b709aee9-d83c-4a50-a58f-89ca1f06a342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
