<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Category</name>
   <tag></tag>
   <elementGuidId>0f36a308-c32c-4180-8d0b-290bc11431b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tslcategorykms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tslcategorykms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb990768-5256-465c-b0cd-3db404d59a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslcategorykms</value>
      <webElementGuid>14b96d63-7b74-4c63-b7ae-a17ee0f104d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>265c54b3-c71a-4269-a8f6-e3170457018c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>f3449040-417b-457e-9d06-bc8df5e833d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Kategori KMS</value>
      <webElementGuid>4b242c3b-b2bf-46e3-9f1a-f4370a6a6ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-full</value>
      <webElementGuid>c0b63c55-e137-41cc-a663-1862da926f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>d1d98302-41af-4443-ad63-9735f548caf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tslcategorykms&quot;)</value>
      <webElementGuid>ccc95c3a-2730-4539-879d-0a0916d6b217</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tslcategorykms']</value>
      <webElementGuid>bda7d134-2741-4579-967a-9b07b0f86e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>99b99f42-15b6-4fc7-85ab-d2ac47d0182f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b655931b-169b-4a91-b5c9-16ffe483777a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tslcategorykms' and @type = 'text' and @name = 'category' and @placeholder = 'Tulis Kategori KMS']</value>
      <webElementGuid>dac9eacf-b7f9-49bb-9a38-6182e55be709</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
