<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchKMSKategori</name>
   <tag></tag>
   <elementGuidId>b7e46614-12cf-4486-8e5b-080dbf32c681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tslsearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tslsearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebf25646-02b7-4a9d-b313-18f470082d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslsearch</value>
      <webElementGuid>3d2f16f4-951b-48ef-a9bb-0aadf9c8a4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2cba131b-e527-4897-a21c-e239b505bf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Judul</value>
      <webElementGuid>fdc00aad-01b9-4c76-acf4-be00c12e7dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none w-full</value>
      <webElementGuid>7d0ff15a-852e-4f5c-8367-8592a19d1690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tslsearch&quot;)</value>
      <webElementGuid>f0205a84-c67e-4ae1-8cde-4e66544b71a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tslsearch']</value>
      <webElementGuid>876705ff-072d-4303-a585-4dbcd5324b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>4a43ab25-c435-4666-885e-b5123f87663a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>01c1114b-894a-4347-86ba-543dd8484ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tslsearch' and @type = 'text' and @placeholder = 'Cari Judul']</value>
      <webElementGuid>9e92bc87-27f6-4d1f-8af1-91e52d79bfed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
