<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_AddLinkQnA</name>
   <tag></tag>
   <elementGuidId>ce610aca-1192-437a-ba61-8edd012ae5cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div[3]/div[2]/div[2]/div/form/div[2]/div[2]/div[2]/div[6]/div/div[${indeks}]/div[1]/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>cdb3c703-ee8b-48e0-b5b3-1f72e286c472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>svg-inline--fa-title-aUACYPxQJa2d</value>
      <webElementGuid>c093eb7c-35b8-41bd-a359-119ff1104b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fas</value>
      <webElementGuid>e363f099-4d4f-494e-829c-eb1ccf800183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>5bae887d-fada-4ed9-ae8a-6578d2825873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-link </value>
      <webElementGuid>e3d421ec-10c8-4a14-aa9c-525d355a5eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1bff854c-a60a-4724-b302-9c7b4cbd7b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>23764719-5fca-4f03-b075-bf0b82bb7b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 640 512</value>
      <webElementGuid>9150a976-355a-4060-b44a-c4316befd363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Link</value>
      <webElementGuid>acf9ec29-7a7f-4333-a15c-5b92bd387571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;pb-8&quot;]/div[2]/div[@class=&quot;flex justify-between items-start gap-2 h-full&quot;]/form[@class=&quot;chatbot-flow-form flex flex-col w-2/4 h-full p-6 bg-white shadow-md rounded-md border border-gray-300 overflow-auto&quot;]/div[@class=&quot;flex gap-6 mb-8&quot;]/div[@class=&quot;card-form flex flex-col w-full shadow-md rounded-lg border border-gray-300 bg-white&quot;]/div[@class=&quot;card-body h-full max-h-full px-6 py-6 overflow-auto&quot;]/div[@class=&quot;flex-1 flex flex-col mb-1&quot;]/div[@class=&quot;mb-3 overflow-auto relative&quot;]/div[@class=&quot;LinkedInput_linked-input__2wnJF answer-option mb-3&quot;]/div[@class=&quot;LinkedInput_input__1zSB6&quot;]/div[@class=&quot;LinkedInput_padding-right__2AFf9&quot;]/div[@class=&quot;LinkedInput_link-icon__1eMj9 btnlinkattach&quot;]/svg[@class=&quot;svg-inline--fa fa-link&quot;]</value>
      <webElementGuid>e050189e-17ac-4c74-8fc0-2eea55e67a04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Jawaban'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>ae3ea5c5-f131-44e7-b4d5-daf3e29d58ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silahkan pilih produk'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>1412336f-a8f2-4db5-9569-ff712a8b43c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link URL'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>8bf7a01d-02a2-4360-b4ff-9de02d41a7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link URL'])[2]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>df36dfa0-4068-4b7a-b788-4e5d6e78eacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[(text() = 'Add Link' or . = 'Add Link')]</value>
      <webElementGuid>548598ce-73a8-444d-af4f-ae9295245960</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
