<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAddAnswer</name>
   <tag></tag>
   <elementGuidId>f9e0b3c2-7e6d-4442-aaeb-284ec01e2c31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnaddanswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnaddanswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6334b9de-ec7c-4c7f-adff-6fe82b12ceec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f55b64c8-6089-4f31-ac75-9e861627cb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnaddanswer</value>
      <webElementGuid>63481a95-b0de-4611-8f09-1a03488a1e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-white rounded border border-darkblue text-darkblue focus:outline-none px-10 py-2</value>
      <webElementGuid>b5f1292a-631f-4498-b79b-b67cd25bde15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah List Jawaban</value>
      <webElementGuid>592d9d64-4a07-4571-bb53-4e87f3a506f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnaddanswer&quot;)</value>
      <webElementGuid>b358a4bc-369b-4c7b-882e-7ff450a52e72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnaddanswer']</value>
      <webElementGuid>26f2471e-bdce-4467-a535-be62496cc1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div[2]/div[2]/div[2]/div[6]/button</value>
      <webElementGuid>3383d76c-d5a3-46dc-b233-934af0b65601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Jawaban'])[1]/following::button[1]</value>
      <webElementGuid>60d1383a-d630-4e3a-b98f-b11553abe196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Otomatis'])[2]/following::button[1]</value>
      <webElementGuid>d7eef6b8-51fd-4479-962f-a3efacbfaf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::button[1]</value>
      <webElementGuid>88a22d03-8afd-4392-9973-c5ecbb1bb266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>47ccdda2-ee35-4693-8d90-10ead03cde47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnaddanswer' and (text() = 'Tambah List Jawaban' or . = 'Tambah List Jawaban')]</value>
      <webElementGuid>11e58899-53d4-4606-9784-7d193191f4af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
