<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnListQnA</name>
   <tag></tag>
   <elementGuidId>f6686b1c-d24a-4e82-9924-7e892f81b4a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.flex.justify-between.items-center.p-4.border-l-8.border-limegreen.rounded-md.mb-3.shadow-md.transition.w-full.duration-200.text-white.bg-white-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@title='${nama_qna}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91b7c33f-4289-4615-8cab-892fb2b9ad4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between items-center p-4 border-l-8 border-limegreen rounded-md mb-3 shadow-md transition w-full duration-200 text-white bg-white-3</value>
      <webElementGuid>5a11799e-7712-4cff-b103-31543296b6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Produk ND6</value>
      <webElementGuid>9fd8b657-3b7e-4358-8fff-8f794cefb1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/flow-chatbot?qnaid=15</value>
      <webElementGuid>f5e450c3-e177-4856-ad7a-cba512544f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Produk ND6</value>
      <webElementGuid>627eeb5e-298d-422a-8538-5d218cff4af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageTemplate&quot;)/div[@class=&quot;w-full h-full max-h-full overflow-auto px-4&quot;]/div[@class=&quot;collapsible bg-white-7 px-4 py-4 shadow-md rounded-md w-full&quot;]/div[@class=&quot;collapsible-body overflow-hidden transition-all duration-200&quot;]/div[@class=&quot;overflow-auto&quot;]/div[@class=&quot;mb-3 overflow-auto relative&quot;]/a[@class=&quot;flex justify-between items-center p-4 border-l-8 border-limegreen rounded-md mb-3 shadow-md transition w-full duration-200 text-white bg-white-3&quot;]</value>
      <webElementGuid>e40ca2c2-3cc7-4c82-a28a-8cf54ad11c3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageTemplate']/div/div[2]/div[2]/div/div/a</value>
      <webElementGuid>129f6259-8161-4107-9031-4429c8694fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanya &amp; Jawab'])[1]/following::a[1]</value>
      <webElementGuid>17f508e6-b3b3-428d-a5b1-55c2e6a3d191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Timeout'])[1]/following::a[1]</value>
      <webElementGuid>15c362a0-a3b2-4b31-bbf7-b15994a45fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/preceding::a[1]</value>
      <webElementGuid>7137f4f0-36d2-41b0-bc96-9ea3f5f24c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings/flow-chatbot?qnaid=15')]</value>
      <webElementGuid>8815274f-118d-46c5-9fb8-3ad79bdfe876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/a</value>
      <webElementGuid>464768df-f858-49f8-b3c0-533d852566fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Produk ND6' and @href = '/settings/flow-chatbot?qnaid=15' and (text() = 'Produk ND6' or . = 'Produk ND6')]</value>
      <webElementGuid>89ae9f39-4c6a-4dd9-a454-467e30a3fd35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
