<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnListQnA</name>
   <tag></tag>
   <elementGuidId>f6686b1c-d24a-4e82-9924-7e892f81b4a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.flex.justify-between.items-center.p-4.border-l-8.border-limegreen.rounded-md.mb-3.shadow-md.transition.w-full.duration-200.text-white.bg-white-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='messageTemplate']/div/div[2]/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>714cc69e-3bd9-45d1-962a-e853a4cd4a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between items-center p-4 border-l-8 border-limegreen rounded-md mb-3 shadow-md transition w-full duration-200 text-white bg-white-3</value>
      <webElementGuid>315d55da-41a3-462f-8c0b-6cb00fd0b5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Produk ND6</value>
      <webElementGuid>93ea2a95-89b8-4293-9b3b-b57e4f9d9d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings/flow-chatbot?qnaid=15</value>
      <webElementGuid>80c18348-56c9-42b4-9b15-99ce19e4bd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Produk ND6</value>
      <webElementGuid>ea1f762e-efae-41a9-81cd-fe55cff6d8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageTemplate&quot;)/div[@class=&quot;w-full h-full max-h-full overflow-auto px-4&quot;]/div[@class=&quot;collapsible bg-white-7 px-4 py-4 shadow-md rounded-md w-full&quot;]/div[@class=&quot;collapsible-body overflow-hidden transition-all duration-200&quot;]/div[@class=&quot;overflow-auto&quot;]/div[@class=&quot;mb-3 overflow-auto relative&quot;]/a[@class=&quot;flex justify-between items-center p-4 border-l-8 border-limegreen rounded-md mb-3 shadow-md transition w-full duration-200 text-white bg-white-3&quot;]</value>
      <webElementGuid>11ccad9e-319b-4f7c-ae24-7671d44bb5fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageTemplate']/div/div[2]/div[2]/div/div/a</value>
      <webElementGuid>2f9df0e9-14bb-458f-a332-151390e76a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanya &amp; Jawab'])[1]/following::a[1]</value>
      <webElementGuid>b448466f-e890-44fd-9259-9aef20f8a1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Timeout'])[1]/following::a[1]</value>
      <webElementGuid>b0af81b4-d11d-44ba-b26f-1febacefe0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/preceding::a[1]</value>
      <webElementGuid>2d10cc6d-5c36-49a0-8ae2-3fd875e61331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings/flow-chatbot?qnaid=15')]</value>
      <webElementGuid>57cc9772-8a9d-40a9-89f4-5f1ea8a221fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/a</value>
      <webElementGuid>1a4c5c79-4cd4-4bc9-afc8-9f123ed72409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Produk ND6' and @href = '/settings/flow-chatbot?qnaid=15' and (text() = 'Produk ND6' or . = 'Produk ND6')]</value>
      <webElementGuid>f0893d0f-79d8-4833-adfb-9e71be570706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
