<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTambah</name>
   <tag></tag>
   <elementGuidId>9c71e0ab-5455-4411-95d7-22ac2ede554b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Tambah' or . = 'Tambah')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;messageTemplate&quot;]/div/div[2]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f8ebb80-90c8-400d-9135-c304ea277a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8db598a6-7e70-4903-9967-f701da1850c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnaddqna w-full bg-white rounded border border-darkblue text-darkblue focus:outline-none px-10 py-2</value>
      <webElementGuid>797a9884-4b12-431b-ba58-8b2200739c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>7f3e919d-6d46-4d09-ac4c-0e21f4e7ae4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageTemplate&quot;)/div[@class=&quot;w-full h-full max-h-full overflow-auto px-4&quot;]/div[@class=&quot;collapsible bg-white-7 px-4 py-4 shadow-md rounded-md w-full&quot;]/div[@class=&quot;collapsible-body overflow-hidden transition-all duration-200&quot;]/div[@class=&quot;overflow-auto&quot;]/a[1]/button[@class=&quot;btnaddqna w-full bg-white rounded border border-darkblue text-darkblue focus:outline-none px-10 py-2&quot;]</value>
      <webElementGuid>d8f87e33-9a9b-44e8-a134-2ed3e7f5765c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>7c45b426-84c2-4a2e-8590-20c8d7b0948f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messageTemplate']/div/div[2]/div[2]/div/a/button</value>
      <webElementGuid>ef0697a0-c735-44ab-8619-610fc1bc3b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ND6 Mutasi/adjust stock - H/A'])[1]/following::button[1]</value>
      <webElementGuid>fb0df910-851b-4466-8c99-353eb45d8061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ND6 Penjualan TO'])[1]/following::button[1]</value>
      <webElementGuid>d134f742-c135-4844-963d-ee3d6878a953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan Pembuka'])[2]/preceding::button[1]</value>
      <webElementGuid>29978552-2a52-4278-965b-7d0f206b4999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b9d1e775-334c-47b2-ac06-1320abcc8383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>68344e8e-171e-4d64-aa15-252f2e74732a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
