<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_JudulTemplateQnA</name>
   <tag></tag>
   <elementGuidId>1dd6766b-decb-4adc-be33-21073fd14816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tsltitlemessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tsltitlemessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2ea542a-f0cc-4a82-903b-c05e03c5438c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0c1f6b25-6ffb-4adb-af73-fe6bd6811a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c87006c0-aca5-462b-823d-82ad1d3c413d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tsltitlemessage</value>
      <webElementGuid>16044322-eecb-4894-987b-be980d33c0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Judul Tanya &amp; Jawab</value>
      <webElementGuid>da2fc5a9-711e-48a2-ac03-c13e87c38607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qnaName</value>
      <webElementGuid>204c78ec-82c2-447d-a60b-efa61c9ef183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>89aeb2ad-9804-4b63-9148-bd45966a61bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tsltitlemessage&quot;)</value>
      <webElementGuid>7eb5f2dc-b8a2-4872-9935-ba3d9c9e116f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tsltitlemessage']</value>
      <webElementGuid>71d0bb08-8ec7-4795-8d5d-cb249f56a451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div/input</value>
      <webElementGuid>8ad40170-61f7-41fe-854f-6fd32382f37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>82e933d0-8ec6-496c-963b-1769537725e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tsltitlemessage' and @placeholder = 'Tulis Judul Tanya &amp; Jawab' and @name = 'qnaName']</value>
      <webElementGuid>097804f3-00fa-4123-834c-d1bbb9a77ba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
