<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AnswerQnA</name>
   <tag></tag>
   <elementGuidId>7b2c7553-7361-487f-88ea-406fc0f9c6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.tslanswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div[2]/div[2]/div[2]/div[6]/div/div[list jawban]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd812bb5-427b-460d-8c11-ce068027421b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tslanswer</value>
      <webElementGuid>877ee0fb-d27d-4ae8-8249-554331da958d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>feefb222-130f-4565-a7b9-76edc9939407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Jawaban</value>
      <webElementGuid>26b869db-0d28-4bf3-a6bd-d3b5d96292a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c034b5b2-cc49-4f7e-81fb-16cb9c78c93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ND6</value>
      <webElementGuid>69468d7e-7b47-4dee-afb2-53001e31d880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;pb-8&quot;]/div[2]/div[@class=&quot;flex justify-between items-start gap-2 h-full&quot;]/form[@class=&quot;chatbot-flow-form flex flex-col w-2/4 h-full p-6 bg-white shadow-md rounded-md border border-gray-300 overflow-auto&quot;]/div[@class=&quot;flex gap-6 mb-8&quot;]/div[@class=&quot;card-form flex flex-col w-full shadow-md rounded-lg border border-gray-300 bg-white&quot;]/div[@class=&quot;card-body h-full max-h-full px-6 py-6 overflow-auto&quot;]/div[@class=&quot;flex-1 flex flex-col mb-1&quot;]/div[@class=&quot;mb-3 overflow-auto relative&quot;]/div[@class=&quot;LinkedInput_linked-input__2wnJF answer-option mb-3&quot;]/div[@class=&quot;LinkedInput_input__1zSB6&quot;]/input[@class=&quot;tslanswer&quot;]</value>
      <webElementGuid>6e4ced03-7ba7-4f58-b10d-1694281f0435</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='ND6']</value>
      <webElementGuid>e4a9553d-a822-4cc9-b412-85fc9cd4612a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div[2]/div[2]/div[2]/div[6]/div/div/div/input</value>
      <webElementGuid>f7de07dc-5954-4e0a-b2b4-f426b96aaaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>3d0f33fd-bd26-4a29-9e08-d614d67012cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Tulis Jawaban']</value>
      <webElementGuid>65e8a199-127f-4ac5-968d-110210966d78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
