<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_PesanOtomatis</name>
   <tag></tag>
   <elementGuidId>fadc75f7-d0e0-41a7-ba45-d0793ffebfc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tmlbotmessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='tmlbotmessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f04c8aef-6187-4bba-8b58-a9998c90f503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control resize-none</value>
      <webElementGuid>c49b1bf6-9037-45c8-8a5d-d5ab42ba56e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tmlbotmessage</value>
      <webElementGuid>9d853c4b-d18b-44f9-85c9-736c0f0325d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>automaticMessage</value>
      <webElementGuid>12f06789-7dd1-4ec2-a3b8-d26478d44538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>57daa32a-201f-41da-b000-cbc895406c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b82426ce-fc55-4ff3-bb35-bc563677002a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Pesan Otomatis</value>
      <webElementGuid>63ea36d2-a87c-4f6a-91ff-5058a4cf650d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tmlbotmessage&quot;)</value>
      <webElementGuid>391c08ba-9ed4-485a-a1b8-f413661b077e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='tmlbotmessage']</value>
      <webElementGuid>2c3d6f4c-b660-426a-9b0a-ada31d687257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div[2]/div[2]/div[2]/div[5]/textarea</value>
      <webElementGuid>7ad81fa5-f38f-4aa9-994d-cfa32121ee64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d5be402d-9827-42f2-8953-35b261e68b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'tmlbotmessage' and @name = 'automaticMessage' and @placeholder = 'Tulis Pesan Otomatis']</value>
      <webElementGuid>f3c3d014-67bf-4fb0-b36c-7037bdb5ce36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
