<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tgl_PesanPertama</name>
   <tag></tag>
   <elementGuidId>cf6f31d7-28b0-4b82-84b5-1015b9beac18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div[2]/div[2]/div[2]/div[1]/label[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f851931-b6df-4a33-91c2-43bdcf9b0abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;pb-8&quot;]/div[2]/div[@class=&quot;flex justify-between items-start gap-2 h-full&quot;]/form[@class=&quot;chatbot-flow-form flex flex-col w-2/4 h-full p-6 bg-white shadow-md rounded-md border border-gray-300 overflow-auto&quot;]/div[@class=&quot;flex gap-6 mb-8&quot;]/div[@class=&quot;card-form flex flex-col w-full shadow-md rounded-lg border border-gray-300 bg-white&quot;]/div[@class=&quot;card-body h-full max-h-full px-6 py-6 overflow-auto&quot;]/div[@class=&quot;checkbox flex items-center justify-between mb-8&quot;]/label[@class=&quot;ToggleSwitch_toggle-switch__1wDmb&quot;]/div[1]</value>
      <webElementGuid>179eae29-1784-42c1-832f-9529b624166e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div[2]/div[2]/div[2]/div[2]/label[2]/div</value>
      <webElementGuid>a7ddcdd2-8cd1-4e5b-90f4-0afc90adde83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label[2]/div</value>
      <webElementGuid>aa3fc4aa-116c-4728-a6d8-e15ecdcd2fa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
