<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tgl_PesanSolusi</name>
   <tag></tag>
   <elementGuidId>b94d9a4e-97ad-4afe-9e33-fa1781898ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div[2]/div[2]/div/form/div[2]/div[2]/div[2]/div[3]/label[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ac1efe5c-ab9b-40b3-bb4f-410db267afff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1693456565021</value>
      <webElementGuid>7c1c3e2a-242f-446b-8a79-4b734c2debf6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
