<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Version1.4.0.0_username</name>
   <tag></tag>
   <elementGuidId>2b067011-a630-4923-bc0d-99cb4a2d0aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tslusername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tslusername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6180a4d6-d6ba-41cc-902b-5d03deb6aef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40beab4d-8362-4f40-ad13-c66eb42e0ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslusername</value>
      <webElementGuid>c5471dd5-bb91-42e3-9e87-f677782c8ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>921468e6-ec46-44eb-b48e-a52588f68736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username / Email</value>
      <webElementGuid>b63e0277-2483-415d-a235-acfefb9b4bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5d5d6d8-02c5-42e1-b5e7-97e25aa2d841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-input-outside w-full h-16 text-center outline-none rounded my-2 px-14</value>
      <webElementGuid>8d2142a3-b9e6-41ef-aad3-f9fb1865fea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tslusername&quot;)</value>
      <webElementGuid>04e92802-6644-41e1-8a72-7dca38a784bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tslusername']</value>
      <webElementGuid>fa140beb-99d0-470a-b88e-df6b3cc1f43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/input</value>
      <webElementGuid>6065826d-a1c9-4f9b-98f1-0b6f5074aef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1d4fbfe4-1f73-4edc-9a42-cc0f395cc720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tslusername' and @name = 'username' and @placeholder = 'Username / Email']</value>
      <webElementGuid>165b99da-789b-49a8-abb5-6c65bb3efed2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
