<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSelanjutnyaUsername</name>
   <tag></tag>
   <elementGuidId>fdf82116-604d-4e0f-9be5-2c8413a30861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-full.bg-white.rounded-b-2xl.px-5.py-10.relative.calculate-layout-user > div.absolute.bottom-5.right-5 > #btnnext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btnnext'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0072d4c-e410-4107-bc8a-ea337808640d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>eb6d9401-de35-4927-9b78-5bd6594ba1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnnext</value>
      <webElementGuid>6f696e5a-5c16-4161-b574-1aab2b6c2a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-lightblue rounded text-white border border-lightblue focus:outline-none w-32 py-2 mt-3 ml-2</value>
      <webElementGuid>4893a5e1-a79d-4f6f-ae4c-544200574f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>9b694d12-8f91-4b0d-a288-bc67b5804a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;user user-add&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;w-full bg-white rounded-b-2xl px-5 py-10 relative calculate-layout-user&quot;]/div[@class=&quot;absolute bottom-5 right-5&quot;]/button[@id=&quot;btnnext&quot;]</value>
      <webElementGuid>0977f4fe-9e94-416b-99a9-58ac4c226a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnnext'])[2]</value>
      <webElementGuid>3b9fbeda-a742-4028-a60e-0f396fb92f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[3]/div/div[2]/button[2]</value>
      <webElementGuid>c26a06a0-c674-4319-9301-0a9af6083041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/following::button[1]</value>
      <webElementGuid>f6e20eaf-1576-4ccb-8c96-d5c2a268c6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::button[2]</value>
      <webElementGuid>93196f28-0aef-45df-bed4-38aa52b635d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::button[1]</value>
      <webElementGuid>d300b8c0-1f20-426b-aa8b-4b61a5af7692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Peran'])[1]/preceding::button[1]</value>
      <webElementGuid>b23246d5-93f7-40fa-8530-d81c7e3d446d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button[2]</value>
      <webElementGuid>77860bde-d1c1-473b-9bac-3b89d4b42c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnnext' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>bc80263a-4a61-410c-8aa0-5b662cbb2f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
