<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTambahUser</name>
   <tag></tag>
   <elementGuidId>c6f40908-6aca-4a6e-982e-b54fa2422dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-full.bg-white.rounded-b-2xl.px-5.py-10.mb-10.relative.calculate-layout-user > div.absolute.bottom-5.right-5 > #btnnext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btnnext'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24c4cd66-d7fb-487b-8612-ff4dbb6f2e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ee058655-ef72-4ea7-b19a-3301fe6b32d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnnext</value>
      <webElementGuid>ff541d7f-0955-40c3-b701-99c4f35a2cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-lightblue rounded text-white border border-lightblue focus:outline-none w-32 py-2 mt-3 ml-2</value>
      <webElementGuid>19818465-3e0f-48c5-81b6-4a713782f218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>6932b07c-4095-47d4-b1f0-fb819a40e668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;user user-add&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;w-full bg-white rounded-b-2xl px-5 py-10 mb-10 relative calculate-layout-user&quot;]/div[@class=&quot;absolute bottom-5 right-5&quot;]/button[@id=&quot;btnnext&quot;]</value>
      <webElementGuid>8104ee59-4204-4c2d-9d54-69097d7b8ef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnnext'])[3]</value>
      <webElementGuid>efaaa907-77c8-4e27-a0a1-a72342701d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[4]/div/div[2]/button[2]</value>
      <webElementGuid>bc0e8453-21e2-432d-ab0a-23c0aaa5777f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[2]/following::button[1]</value>
      <webElementGuid>f057b0a4-6eab-48ca-ba81-5370cb82f472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Data Group'])[1]/following::button[2]</value>
      <webElementGuid>c011f472-22d4-4e7e-95ac-17e574c14e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::button[1]</value>
      <webElementGuid>485030ef-4d11-48d4-b88b-cce7b405f254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nexsoft'])[2]/preceding::button[1]</value>
      <webElementGuid>981758d2-aa2d-48d3-8e7e-fa9f522c6bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah']/parent::*</value>
      <webElementGuid>fa26a7e7-c281-49da-b0e4-8fab307d14a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/button[2]</value>
      <webElementGuid>ce11f270-61ad-40f1-a816-b1be7168a662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnnext' and (text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>eefeb9f2-5fbc-4d7e-8fb9-32bed72b637f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
