<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnUbah</name>
   <tag></tag>
   <elementGuidId>32c40bfa-535b-48f6-b2f4-ef78bac363f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.w-full.bg-white.rounded-b-2xl.px-5.py-10.mb-10.relative.calculate-layout-user > div.absolute.bottom-5.right-5 > #btnnext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='btnnext'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56575386-72ea-418b-b822-738282bfd26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9824fc91-f59a-45a7-be94-1603ef409037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnnext</value>
      <webElementGuid>f6a1bf2e-098b-4d31-8e3f-5e749e12496e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-lightblue rounded text-white border border-lightblue focus:outline-none w-32 py-2 mt-3 ml-2</value>
      <webElementGuid>5676573e-db56-4831-b1d8-44c125cf750e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>81f3ee95-eca4-4691-90cf-21befe2e9d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;user user-edit&quot;]/div[@class=&quot;block&quot;]/div[@class=&quot;w-full bg-white rounded-b-2xl px-5 py-10 mb-10 relative calculate-layout-user&quot;]/div[@class=&quot;absolute bottom-5 right-5&quot;]/button[@id=&quot;btnnext&quot;]</value>
      <webElementGuid>4b0765f4-e95c-4866-896f-f35703d02b34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnnext'])[3]</value>
      <webElementGuid>086fc144-8b14-4627-a7f8-b1067dcf5654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[4]/div/div[2]/button[2]</value>
      <webElementGuid>ea46679a-c022-4f7c-846b-d91197d9b3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[2]/following::button[1]</value>
      <webElementGuid>88e58b66-d0a9-4c52-b9a5-622ae41cff59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nexsoft'])[1]/following::button[2]</value>
      <webElementGuid>f9979688-da4f-43d3-aefe-76c404cd6b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>ada7b8b7-5976-4527-ab5b-88cc2de22faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>7e1b1469-6eea-4464-a539-c5737e9a840f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah']/parent::*</value>
      <webElementGuid>f6f9a001-28b7-42dc-bb3d-ed3a1bb03cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/button[2]</value>
      <webElementGuid>f73bb38b-2319-4454-be68-02a911bfb766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnnext' and (text() = 'Ubah' or . = 'Ubah')]</value>
      <webElementGuid>752aa9df-3dd5-44b9-886b-eafeee479ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
