<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Periode</name>
   <tag></tag>
   <elementGuidId>ce363b7f-e00e-4b2f-8c1e-642d29a46457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnperiode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnperiode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c69f925b-840d-4979-a42b-6ba11fdd5b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnperiode</value>
      <webElementGuid>15136c77-a74f-44aa-b608-4cb223adf2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between items-center cursor-pointer p-2</value>
      <webElementGuid>a87e128d-e961-485f-8d4b-c28e9253b737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Periode </value>
      <webElementGuid>16762c92-21c3-42f7-a5f4-ad1ec8fe2fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnperiode&quot;)</value>
      <webElementGuid>9c9e50fa-c51a-4ce0-8e45-bf087214aa44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnperiode']</value>
      <webElementGuid>45c2c543-d239-4d70-af2c-bbdb77f2dfb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div/div/div[2]/div[3]</value>
      <webElementGuid>cfafc9d2-16d3-4f2e-ab11-5d6b9f335651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/following::div[2]</value>
      <webElementGuid>500b10f7-77c7-476c-97ed-e9dd110e61e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Nexcare'])[1]/following::div[3]</value>
      <webElementGuid>9cfb7754-0fde-4fa8-9298-1def0dfb8c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[3]</value>
      <webElementGuid>ee5e8531-6876-425a-97a4-bde94621f367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btnperiode' and (text() = ' Periode ' or . = ' Periode ')]</value>
      <webElementGuid>33a644c2-afd9-4c72-b229-9e3f97fff62e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
