<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_TambahBerita</name>
   <tag></tag>
   <elementGuidId>7d695323-f098-42be-aac9-4a63d690b9db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnadd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnadd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>08a01c51-de67-4e52-b13d-51c7797fdc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnadd</value>
      <webElementGuid>b2f41963-ee34-40e8-a3ab-db3129b94d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center cursor-pointer bg-olddarkblue text-white py-2 px-6 rounded-lg</value>
      <webElementGuid>294da0ed-c820-4cdf-90c2-4de226953e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Berita</value>
      <webElementGuid>7b5fae18-8bc9-48e7-ae5f-204aa6773ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnadd&quot;)</value>
      <webElementGuid>936f927d-1cae-4919-93d7-93896d9c8799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnadd']</value>
      <webElementGuid>32be19a0-5765-4903-917b-73047bf8c2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>1b9bc5bd-96a0-43ca-a527-59df53335f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berita'])[3]/following::div[6]</value>
      <webElementGuid>232c9b23-fc29-4166-bc54-96791d9164a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berita'])[2]/following::div[8]</value>
      <webElementGuid>0f5a67e7-216d-4183-8882-ebdc0387f7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::div[1]</value>
      <webElementGuid>ceb072e9-3ae5-44c5-b630-00a9e1619725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>11c52b1f-d3c2-4ecd-924b-d3beea26cb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btnadd' and (text() = 'Tambah Berita' or . = 'Tambah Berita')]</value>
      <webElementGuid>6b2a897d-ddd1-43bd-8e26-a778f0fd2b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
