<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link</name>
   <tag></tag>
   <elementGuidId>34688e71-c7ab-434b-a1e2-4c2ed2311c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tslurllink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tslurllink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f9402a7-3975-4767-9dd6-f9f990fd862d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslurllink</value>
      <webElementGuid>117babd3-7a80-44d4-82b1-c941cda83891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a91f58e-dff3-4309-8028-18f4d0491319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>urlLink</value>
      <webElementGuid>03040ee9-dc00-4680-ae23-4686bf873071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Link Url</value>
      <webElementGuid>8c67705f-9fc3-41e6-afed-8d3abbe725c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-full</value>
      <webElementGuid>17e33982-b9c4-40a8-9efb-2cae9cc71b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>98c4f780-1d3d-454a-9aba-5945a26e7bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tslurllink&quot;)</value>
      <webElementGuid>d9b6f5d2-05a0-47da-aaa8-dd7110b6a43a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tslurllink']</value>
      <webElementGuid>7186855e-bf8b-47ef-afa0-69d75b03dafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div/div/div/div[4]/input</value>
      <webElementGuid>3dd32e1e-c8b0-4183-a681-ce28768fb45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>2c1c039d-497a-4a8c-b4f0-b899f15fb0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tslurllink' and @type = 'text' and @name = 'urlLink' and @placeholder = 'Tulis Link Url']</value>
      <webElementGuid>8ac68bb1-5a9c-4119-8a6d-004aa2df465e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
