<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchBerita</name>
   <tag></tag>
   <elementGuidId>c163b6b7-cbd3-4cc1-bdbd-e65fef100efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tslsearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tslsearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>686408b7-8f6f-45ab-9753-c9d9178d2d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tslsearch</value>
      <webElementGuid>5352c234-4f94-4ac1-8bf3-4e5ede0a25fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ced48b5-66d0-476a-8eff-5c45169a6d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Judul</value>
      <webElementGuid>62c56e2b-6a76-438b-847b-b992add9c35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none w-full</value>
      <webElementGuid>6c5d2ec9-6258-44a1-8bf9-25179884f8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tslsearch&quot;)</value>
      <webElementGuid>391fb0ae-95dc-41d3-8c8f-e1b9f441f3cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tslsearch']</value>
      <webElementGuid>94e3dfb8-5c50-4451-94d4-1423df8f0951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>f2e4b829-8e99-4eef-bf3f-21e7e36b78e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c87e8a61-7940-4406-b783-32c036a3063a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tslsearch' and @type = 'text' and @placeholder = 'Cari Judul']</value>
      <webElementGuid>85b6a1c1-c039-45f9-9bcd-3f85629a7fde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
