<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description</name>
   <tag></tag>
   <elementGuidId>00ec0ef8-2756-4b74-9c4c-8e645602561f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tsldescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='tsldescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>01a6dfa8-0aa8-462e-825f-621d8aa561c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tsldescription</value>
      <webElementGuid>d36abac7-ad42-4bac-84f9-bdb29999e343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4bea801b-cb2c-486c-b61a-eaf555994a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>de06ad99-7a38-44ce-9315-775fa796cae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis Deskripsi</value>
      <webElementGuid>9e06137b-886e-462d-8dba-4fac77663a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control w-full resize-none h-60</value>
      <webElementGuid>a4983d03-271c-4358-bb59-8b488956baa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tsldescription&quot;)</value>
      <webElementGuid>b4ff91c5-24c5-49de-b2e5-5d037a51af20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='tsldescription']</value>
      <webElementGuid>fe7ce58e-f864-4986-bc9f-d9c3f6b18be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div/div/div/div/div[2]/textarea</value>
      <webElementGuid>2fd03d97-2097-4579-9ce0-cc1d5ab4b458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>693b9e99-a712-40cb-acbc-9a823820010d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'tsldescription' and @type = 'textarea' and @name = 'description' and @placeholder = 'Tulis Deskripsi']</value>
      <webElementGuid>04cd61d6-b976-48a1-8853-3dba595a6191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
