<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Judul</name>
   <tag></tag>
   <elementGuidId>115de5ba-0b8f-4385-bfbe-5134a125db1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div[2]/div/div/div[2]/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4bf0257e-f5cb-4c45-a18d-51fd445c972d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium</value>
      <webElementGuid>837aaa1c-b2be-4911-acd4-f3efb29f5a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>adawd12</value>
      <webElementGuid>3cfc1688-db7e-4b11-b47e-63ad69933bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;h-full pb-12&quot;]/div[@class=&quot;h-content&quot;]/div[@class=&quot;white-container pt-5 h-full&quot;]/div[@class=&quot;w-full h-full bg-white border border-gray-300 rounded-lg p-8 flex item center text-gray-700&quot;]/div[@class=&quot;w-1/4 pr-20&quot;]/div[@class=&quot;mb-5&quot;]/p[@class=&quot;font-medium&quot;]</value>
      <webElementGuid>6d6e08d1-9c6c-4573-8539-08904e2af792</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div[2]/div/div/div[2]/p[2]</value>
      <webElementGuid>2d0d9789-1dac-4539-a082-6b6f544f6c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::p[5]</value>
      <webElementGuid>f80f9cfa-748f-47e3-a732-2851ab84e02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin NexCare'])[2]/following::p[5]</value>
      <webElementGuid>4a8cd162-0a9f-4412-b328-6b69d7c1d357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asda'])[1]/preceding::p[2]</value>
      <webElementGuid>52ef908e-5242-4c9d-acba-c9153229465b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.youtube.com/watch?v=xvFZjo5PgG0'])[1]/preceding::p[5]</value>
      <webElementGuid>ee83dd72-a660-4f93-9a9c-032125f5c651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='adawd12']/parent::*</value>
      <webElementGuid>da3aeaa1-83ab-46fd-88f3-c6ab80ab2e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[2]</value>
      <webElementGuid>174ee9f8-078b-4992-8c49-3e81746bb775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'adawd12' or . = 'adawd12')]</value>
      <webElementGuid>5992ba9d-cd4a-48e2-a544-7d57cb623945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
