<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Status</name>
   <tag></tag>
   <elementGuidId>a24b6617-9a7a-4734-a60d-faf54a05a504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div[2]/div/div[2]/div[3]/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4de9e094-1e54-46f4-99d1-5aac7217de0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium</value>
      <webElementGuid>3a3dfc83-d1f0-41ac-b912-b9e3ed94aa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktif</value>
      <webElementGuid>db841d80-c690-4fdc-89fa-952eb2f2abc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;h-full pb-12&quot;]/div[@class=&quot;h-content&quot;]/div[@class=&quot;white-container pt-5 h-full&quot;]/div[@class=&quot;w-full h-full bg-white border border-gray-300 rounded-lg p-8 flex item center text-gray-700&quot;]/div[@class=&quot;w-1/4 pr-20&quot;]/div[@class=&quot;mb-5&quot;]/p[@class=&quot;font-medium&quot;]</value>
      <webElementGuid>fb21a767-d8a5-4196-8f49-12af44edd112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div[2]/div/div[2]/div[3]/p[2]</value>
      <webElementGuid>1ad23547-22e1-4f79-8555-b4709a3a484a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.youtube.com/watch?v=xvFZjo5PgG0'])[1]/following::p[2]</value>
      <webElementGuid>a9a9ce53-c8ea-4b06-8bde-4c200c958a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asda'])[1]/following::p[5]</value>
      <webElementGuid>217a9896-53e0-4ecf-ae18-f44bd4be5937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[1]/preceding::p[5]</value>
      <webElementGuid>79d36630-6701-47d7-bed9-0bfb9717e011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created by'])[1]/preceding::p[6]</value>
      <webElementGuid>5c062586-ff16-459b-acee-b0f4c41e7247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aktif']/parent::*</value>
      <webElementGuid>5b19f7ad-b155-4ccc-8598-65e8676518a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p[2]</value>
      <webElementGuid>76f14cb8-7d5c-47d4-8296-1fd6ac53535e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Aktif' or . = 'Aktif')]</value>
      <webElementGuid>b174a670-490c-4727-86cf-96505895d291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
