<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Link</name>
   <tag></tag>
   <elementGuidId>8f94b870-b566-47c2-a93e-7d4fafbf2106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mb-5 > a.font-medium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div[2]/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a177a22-33e3-47dc-ad9f-67dca2eca272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.youtube.com/watch?v=xvFZjo5PgG0</value>
      <webElementGuid>b3dbaf25-7308-4cca-80fc-2c9b270cfcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c59d9aeb-1d5f-47c5-ac66-d9f6ad0d6abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>4314aa05-adb0-42b6-95c8-08576d2fcd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium</value>
      <webElementGuid>b0797a7b-9486-499a-b7e6-1b90c670b40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.youtube.com/watch?v=xvFZjo5PgG0</value>
      <webElementGuid>29a52650-63b5-4c4f-a144-35cf441c1b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-layout&quot;]/div[@class=&quot;main-layout px-10 overflow-auto&quot;]/div[@class=&quot;h-full pb-12&quot;]/div[@class=&quot;h-content&quot;]/div[@class=&quot;white-container pt-5 h-full&quot;]/div[@class=&quot;w-full h-full bg-white border border-gray-300 rounded-lg p-8 flex item center text-gray-700&quot;]/div[@class=&quot;w-1/4 pr-20&quot;]/div[@class=&quot;mb-5&quot;]/a[@class=&quot;font-medium&quot;]</value>
      <webElementGuid>a2e8de7e-642c-48e8-bd22-4536921f6f4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/div[2]/div[2]/div/div[2]/div[2]/a</value>
      <webElementGuid>a0f96ec4-1f1b-4d5f-826a-8ff370a3a362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://www.youtube.com/watch?v=xvFZjo5PgG0')]</value>
      <webElementGuid>2da33368-5ba2-40c7-bc60-7be0e774952c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asda'])[1]/following::a[1]</value>
      <webElementGuid>0e82f13e-aa07-4739-b87f-561d309920c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::a[1]</value>
      <webElementGuid>3da2ea0d-e76b-476e-895d-e6689bf3ffa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[1]/preceding::a[1]</value>
      <webElementGuid>f4932cbe-dc2a-4795-b56b-978f08a6e4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created by'])[1]/preceding::a[1]</value>
      <webElementGuid>6c621fe1-0e75-436f-ac8d-44672dcf9d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://www.youtube.com/watch?v=xvFZjo5PgG0']/parent::*</value>
      <webElementGuid>847d943b-3af2-41ec-8f01-a175003d4694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.youtube.com/watch?v=xvFZjo5PgG0')]</value>
      <webElementGuid>f957ad45-b0e0-4e07-8dc1-2b00a8ba4c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div[2]/a</value>
      <webElementGuid>36ec4730-732e-42e4-92b2-53fa20e2f3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.youtube.com/watch?v=xvFZjo5PgG0' and (text() = 'https://www.youtube.com/watch?v=xvFZjo5PgG0' or . = 'https://www.youtube.com/watch?v=xvFZjo5PgG0')]</value>
      <webElementGuid>e4dc4adc-4a60-4a1a-a31c-e5d4be567535</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
